import {test,expect,type Page} from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';

async function api(page:Page,url:string,body?:unknown,method='POST'){
  return page.evaluate(async({url,body,method})=>{const session=await(await fetch('/api/session')).json();const response=await fetch('/api'+url,body===undefined?{}:{method,headers:{'Content-Type':'application/json','X-CSRF':session.csrf},body:JSON.stringify(body)});if(!response.ok)throw new Error(await response.text());return response.json();},{url,body,method});
}
const id=()=>crypto.randomUUID().replaceAll('-','');
const day=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;

test('My page preserves real tasks, versioned undo, a pinned live app, drafts and narrow-screen access',async({page})=>{
  test.setTimeout(90000);page.setDefaultTimeout(10000);
  await page.setViewportSize({width:1440,height:1000});await page.goto('/');
  await page.getByLabel('Host access key',{exact:true}).fill(fs.readFileSync(path.resolve(process.env.THADDEUS_TEST_DATA!,'host-key.txt'),'utf8').trim());
  await page.getByRole('button',{name:'Unlock study',exact:true}).click();
  const composer=page.getByLabel('Message or goal');await expect(composer).toBeVisible();
  await page.getByRole('button',{name:'Open My page',exact:true}).click();
  const today=page.getByRole('region',{name:'My page',exact:true});await expect(today.getByRole('heading',{name:'Today',exact:true})).toBeVisible();
  const sideTabs=page.getByRole('navigation',{name:'Log views'});
  const todayWidth=(await page.getByRole('complementary',{name:'Activity log'}).boundingBox())!.width;
  await page.clock.install({time:new Date('2026-09-22T23:59:55')});
  const date=day(new Date('2026-09-22T12:00:00'));
  const create=(title:string,tracking:any,due:string|null=null)=>api(page,'/library/'+id(),{kind:'todo',title,content:'',status:'open',url:null,due,version:'absent',tracking},'PUT');
  const task=await create('Review the preview',{section:'daily',cadence:'none'});
  await create('Overdue weekly work',{section:'weekly',cadence:'none'},'2026-09-21');
  await create('Tomorrow’s walk',{section:'daily',cadence:'daily',lastCheckIn:date,nextCheckIn:'2026-09-23'});
  await create('Later work',{section:'weekly',cadence:'none'},'2026-09-30');
  await expect(today.getByRole('button',{name:'Mark complete: Review the preview',exact:true})).toBeVisible();
  await expect(today.getByText('Overdue weekly work',{exact:true})).toBeVisible();
  await expect(today.getByText('Later work',{exact:true})).toHaveCount(0);
  await expect(today.getByText('Tomorrow’s walk',{exact:true})).toHaveCount(0);
  await page.clock.fastForward(6000);
  await expect(today.getByText('Tomorrow’s walk',{exact:true})).toBeVisible();
  await expect(today.getByText('Review the preview',{exact:true})).toBeVisible();
  await today.getByRole('button',{name:'Mark complete: Review the preview',exact:true}).click();
  await expect(today.getByRole('button',{name:'Undo',exact:true})).toBeEnabled();
  expect((await api(page,'/state')).library.find((item:any)=>item.id===task.id).status).toBe('done');
  await today.getByRole('button',{name:'Undo',exact:true}).click();
  await expect(today.getByRole('button',{name:'Mark complete: Review the preview',exact:true})).toBeVisible();
  await today.getByRole('button',{name:'Mark complete: Review the preview',exact:true}).click();
  const newer=(await api(page,'/state')).library.find((item:any)=>item.id===task.id);
  await api(page,'/library/'+task.id,{...newer,content:'Another window edited this'},'PUT');
  await expect(today.getByRole('button',{name:'Undo',exact:true})).toBeDisabled();
  await expect(today.getByText('No task is running. Your list waits for your instructions.',{exact:true})).toBeVisible();

  const appId=id();const definition={title:'My daily list',description:'Fictional test app',fields:[{key:'text',label:'Text',kind:'text'}],summaries:[],page:{html:'<main><label>App draft<input id="draft"></label><p id="count"></p></main>',css:'main{padding:20px;color:var(--text)}',javaScript:"thaddeus.onChange(state=>document.getElementById('count').textContent=state.entries.length+' records');"}};
  const app=await api(page,'/artifacts/'+appId,{operationId:id(),version:'absent',definition,upserts:[]},'PUT');
  await composer.fill('Keep this unfinished message');
  const state=await api(page,'/state');await api(page,'/my-page',{mode:'artifact',artifactId:appId,version:state.myPage.version},'PUT');
  await expect(page.getByRole('heading',{name:'My daily list',exact:true})).toBeVisible();
  await expect(composer).toHaveValue('Keep this unfinished message');
  await expect(sideTabs.getByRole('button',{name:'Pinned app: My daily list',exact:true})).toHaveAttribute('aria-pressed','true');
  expect((await page.getByRole('region',{name:'Artifact page',exact:true}).boundingBox())!.width).toBe(todayWidth);
  await sideTabs.getByRole('button',{name:'Activity',exact:true}).click();
  await expect(sideTabs.getByRole('button',{name:'Activity',exact:true})).toHaveAttribute('aria-pressed','true');
  await expect(composer).toHaveValue('Keep this unfinished message');
  await sideTabs.getByRole('button',{name:'Pinned app: My daily list',exact:true}).click();
  const frame=page.frameLocator('iframe');await frame.getByLabel('App draft').fill('Keep my app draft');
  const saved=await api(page,'/artifacts/'+appId,{operationId:id(),version:app.version,upserts:[{id:'',values:{text:'Fresh update'}}]},'PUT');
  await expect(frame.getByText('1 records',{exact:true})).toBeVisible();await expect(frame.getByLabel('App draft')).toHaveValue('Keep my app draft');
  await api(page,'/artifacts/'+appId,{operationId:id(),version:saved.version,definition:{...definition,page:{...definition.page,html:definition.page.html+'<p>New design</p>'}}},'PUT');
  await expect(page.getByText(/An updated design is ready/)).toBeVisible();
  await expect(frame.getByLabel('App draft')).toHaveValue('Keep my app draft');
  page.once('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:'Load updated design',exact:true}).click();
  await expect(frame.getByText('New design',{exact:true})).toBeVisible();
  fs.mkdirSync(process.env.THADDEUS_SCREENSHOTS!,{recursive:true});
  await page.screenshot({path:path.join(process.env.THADDEUS_SCREENSHOTS!,'my-page-pinned-desktop.png'),animations:'disabled'});
  await page.getByRole('button',{name:'Full screen',exact:true}).click();await expect(composer).toBeHidden();
  await page.getByRole('button',{name:'Show chat',exact:true}).click();await expect(composer).toHaveValue('Keep this unfinished message');
  await page.getByRole('button',{name:'Close app',exact:true}).click();
  await page.reload();await expect(page.getByRole('heading',{name:'My daily list',exact:true})).toBeVisible();
  await expect(composer).toHaveValue('Keep this unfinished message');
  const pinnedBefore=(await api(page,'/state')).myPage;
  await page.getByRole('button',{name:'Back to Today',exact:true}).click();
  await expect(today.getByRole('heading',{name:'Today',exact:true})).toBeVisible();
  expect((await api(page,'/state')).myPage).toEqual(pinnedBefore);
  await sideTabs.getByRole('button',{name:'Pinned app: My daily list',exact:true}).click();
  await sideTabs.getByRole('button',{name:'Today',exact:true}).click();
  await expect(today.getByRole('heading',{name:'Today',exact:true})).toBeVisible();
  expect((await api(page,'/state')).myPage).toEqual(pinnedBefore);
  await today.getByRole('button',{name:'Remove pin',exact:true}).click();
  await expect(sideTabs.getByRole('button',{name:'Pinned app: My daily list',exact:true})).toHaveCount(0);
  expect((await api(page,'/state')).myPage.mode).toBe('today');
  fs.mkdirSync(process.env.THADDEUS_SCREENSHOTS!,{recursive:true});
  await page.screenshot({path:path.join(process.env.THADDEUS_SCREENSHOTS!,'my-page-desktop.png'),animations:'disabled'});
  await today.getByRole('button',{name:'Choose an app instead',exact:true}).click();
  await page.getByRole('button',{name:'Pin to My page',exact:true}).click();
  await expect(page.getByRole('heading',{name:'My daily list',exact:true})).toBeVisible();
  expect((await api(page,'/state')).myPage.artifactId).toBe(appId);
  const otherId=id();await api(page,'/artifacts/'+otherId,{operationId:id(),version:'absent',definition:{...definition,title:'Temporary other app'},upserts:[]},'PUT');
  await page.getByRole('button',{name:'Close app',exact:true}).click();
  await page.getByRole('button',{name:'Expand sidebar',exact:true}).click();
  await page.getByRole('navigation',{name:'Study navigation'}).getByRole('button',{name:'Artifacts',exact:true}).click();
  await page.getByRole('button',{name:'Open Temporary other app',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Temporary other app',exact:true})).toBeVisible();
  expect((await api(page,'/state')).myPage.artifactId).toBe(appId);
  await page.getByRole('button',{name:'Show chat',exact:true}).click();
  await page.getByRole('button',{name:'Open My page',exact:true}).click();
  await expect(page.getByRole('heading',{name:'My daily list',exact:true})).toBeVisible();
  await expect(composer).toHaveValue('Keep this unfinished message');
  await page.getByRole('button',{name:'Back to Today',exact:true}).click();
  await page.setViewportSize({width:390,height:844});
  await page.getByRole('button',{name:'Open My page',exact:true}).click();
  await expect(page.getByRole('heading',{name:'My daily list',exact:true})).toBeVisible();
  await expect(sideTabs.getByRole('button',{name:'Pinned app: My daily list',exact:true})).toHaveAttribute('aria-pressed','true');
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:path.join(process.env.THADDEUS_SCREENSHOTS!,'my-page-pinned-mobile.png'),animations:'disabled'});
  await page.getByRole('button',{name:'Back to Today',exact:true}).click();
  await expect(today.getByRole('heading',{name:'Today',exact:true})).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  fs.mkdirSync(process.env.THADDEUS_SCREENSHOTS!,{recursive:true});await page.screenshot({path:path.join(process.env.THADDEUS_SCREENSHOTS!,'my-page-mobile.png'),animations:'disabled'});
  await page.getByRole('button',{name:'Close activity log',exact:true}).click();await expect(composer).toHaveValue('Keep this unfinished message');
  const final=await api(page,'/state');expect(final.runs).toHaveLength(0);expect(final.delegations).toHaveLength(0);expect(final.search.budget.used).toBe(0);
});
