import {test,expect} from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';

test('native research through question, exact import approval and reviewed workspace removal',async({page})=>{
  test.skip(process.env.THADDEUS_NATIVE_RESEARCH!=='1','Explicit owned VM fixture only; no automatic virtualization or model dispatch.');
  test.setTimeout(600000);
  const root=path.resolve(process.env.THADDEUS_TEST_DATA!);
  const hostKey=fs.readFileSync(path.join(root,'host-key.txt'),'utf8').trim();
  await page.goto('/');await page.getByLabel('Host access key',{exact:true}).fill(hostKey);
  await page.getByRole('button',{name:'Unlock study'}).click();
  await page.getByRole('button',{name:'Settings',exact:true}).click();
  const setup=page.getByRole('region',{name:'Host research setup'});
  await expect(setup.getByRole('button',{name:'Enable research on this host'})).toBeDisabled();
  await setup.getByRole('button',{name:'Check installed worker'}).click();
  await expect(setup.getByRole('button',{name:'Enable research on this host'})).toBeEnabled({timeout:60000});
  const checked=await page.evaluate(async()=>(await fetch('/api/state')).json());
  expect(checked.research.enabled).toBe(false);expect(checked.runs).toHaveLength(0);
  await setup.getByRole('button',{name:'Enable research on this host'}).click();
  await expect(setup.getByRole('button',{name:'Disable new research'})).toBeEnabled();
  for(const width of [1440,390]){
    await page.setViewportSize({width,height:1000});await setup.screenshot({path:path.join(root,`host-setup-${width}.png`)});
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
  }
  await page.reload();await page.getByRole('button',{name:'Settings',exact:true}).click();
  await expect(page.getByRole('region',{name:'Host research setup'}).getByRole('button',{name:'Disable new research'})).toBeEnabled();
  await page.getByRole('button',{name:'Knowledge',exact:true}).click();
  const memory=page.getByRole('group',{name:'Remembered context'});await memory.locator('summary').first().click();
  await memory.getByLabel('Source note',{exact:true}).selectOption('notes/memory-source.md');
  await memory.getByLabel('Remembered statement').fill('Use cobalt workshop handouts.');
  await memory.getByLabel('Exact source quotation').fill('The workshop handout color is cobalt.');
  await memory.getByRole('button',{name:'Remember this statement'}).click();await expect(memory.locator('[data-memory-id]')).toHaveCount(1);
  await memory.getByLabel('Remembered statement').fill('The spare notebook is jade.');
  await memory.getByLabel('Exact source quotation').fill('The spare notebook is jade.');
  await memory.getByRole('button',{name:'Remember this statement'}).click();await expect(memory.locator('[data-memory-id]')).toHaveCount(2);
  await page.getByRole('button',{name:'Home',exact:true}).click();
  await page.getByLabel('Message mode').selectOption('research');
  await expect(page.getByRole('region',{name:'Research scope'})).toBeVisible();
  await expect(page.getByRole('checkbox',{name:'notes/source.md'})).toBeChecked();
  await page.getByRole('checkbox',{name:'notes/memory-source.md'}).uncheck();
  await page.getByRole('checkbox',{name:'Use cobalt workshop handouts.',exact:true}).check();
  await expect(page.getByRole('checkbox',{name:'The spare notebook is jade.',exact:true})).not.toBeChecked();
  await page.getByLabel('Public source websites (optional)').fill('docs.docker.com');
  await page.getByText('Resource limits & provider guarantees',{exact:true}).click();
  await page.getByLabel('Model calls',{exact:true}).fill('8'); // Explicit fixture allowance; product defaults remain unchanged.
  await page.getByLabel('Message or goal').fill('Read notes/source.md and https://docs.docker.com/ai/sandboxes/faq/. Ask which workshop audience to use, then write summary.md and request its import to plans/summary.md with captured citations. This is a fictional integration fixture.');
  await page.screenshot({path:path.join(root,'research-composer.png'),fullPage:true});
  await page.getByRole('button',{name:'Start research'}).click();
  const progress=page.getByRole('region',{name:'Research progress'});
  await expect(page.getByRole('heading',{name:'A detail before I continue.'})).toBeVisible({timeout:180000});
  const answer=page.getByRole('button',{name:'Send answer & continue'});
  await expect(page.getByRole('button',{name:'Developers',exact:true})).toBeEnabled({timeout:180000});
  await page.reload(); // Durable question and stopped worker are recovered by the normal UI state request.
  await page.getByRole('button',{name:'Tasks',exact:true}).click();
  await page.locator('[data-run-id]').first().click();
  await page.getByRole('button',{name:'Developers',exact:true}).click();
  await page.screenshot({path:path.join(root,'research-question.png'),fullPage:true});
  await answer.click();
  await expect(page.getByRole('button',{name:'Approve exact write'})).toBeEnabled({timeout:180000});
  await expect(progress.getByText('Artifact readback matched: summary.md',{exact:true})).toBeVisible();
  const quotationChecks=page.getByRole('region',{name:'Source quotation checks'});
  await expect(quotationChecks.getByText('Proposal 1 · Correction requested',{exact:true})).toBeVisible();
  await expect(quotationChecks.getByText('Proposal 2 · Quotation checks passed',{exact:true})).toBeVisible();
  const captures=page.getByRole('region',{name:'Captured worker files'});
  await expect(captures.getByText('Source correction sent to OpenClaw',{exact:false})).toBeVisible();
  await expect(captures.getByText('Captured file ready for your approval',{exact:false})).toBeVisible();
  const before=await page.evaluate(async()=>({status:(await fetch('/api/knowledge?path=plans/summary.md')).status}));
  expect(before.status).toBe(404);
  for(const width of [1440,390]){
    await page.setViewportSize({width,height:1000});
    await page.screenshot({path:path.join(root,`research-approval-${width}.png`),fullPage:true});
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
  }
  await page.getByRole('button',{name:'Approve exact write'}).click();
  await expect(progress.getByText('Worker stopped · private workspace retained for inspection',{exact:true})).toBeVisible({timeout:60000});
  await page.getByRole('button',{name:'Open editable plan'}).click();
  await expect(page.getByLabel('Markdown editor')).toContainText('Audience: Developers');
  const exported=await page.evaluate(async()=>(await fetch('/api/export')).json());
  expect(exported.runs[0].research.phase).toBe('finished');
  expect(exported.runs[0].research.review.artifact).toBe('summary.md');
  expect(exported.runs[0].goal.criteria.some((criterion:any)=>criterion.status==='unverified')).toBeTruthy();
  expect(exported.runs[0].modelCalls).toBe(7);
  expect(exported.runs[0].repairs).toBe(1);
  expect(exported.runs[0].nativeProposals.map((review:any)=>review.status)).toEqual(['repair-requested','passed']);
  expect(exported.runs[0].nativeProposals[1].contentHash).toBe(exported.runs[0].research.review.sha256);
  expect(exported.runs[0].profile.proposalEvidenceVersion).toBe(2);
  expect(exported.runs[0].artifactImports.map((item:any)=>item.status)).toEqual(['repair-dispatched','ready-for-approval']);
  expect(exported.runs[0].artifactImports[0].approvalId).toBeNull();
  expect(exported.runs[0].artifactImports[1].sha256).toBe(exported.runs[0].research.review.sha256);
  expect(exported.runs[0].executionCommands.filter((command:any)=>command.kind==='artifact-repair')).toHaveLength(1);
  expect(exported.runs[0].preparedContext.memories).toHaveLength(1);
  expect(exported.runs[0].preparedContext.memories[0].statement).toBe('Use cobalt workshop handouts.');
  fs.writeFileSync(path.join(root,'browser-export.json'),JSON.stringify(exported,null,2));
  await page.getByRole('button',{name:'Settings',exact:true}).click();
  const storage=page.getByRole('region',{name:'Stored research workspaces'});
  await storage.getByRole('button',{name:'Inspect stored workspace',exact:true}).click();
  const review=storage.getByRole('region',{name:'Workspace removal review'});
  await expect(review.getByRole('heading')).toHaveText(exported.runs[0].goal.objective);
  const remove=review.getByRole('button',{name:'Remove reviewed workspace'});
  await expect(remove).toBeDisabled();
  await review.getByLabel('Confirm workspace removal').fill('REMOVE'); await expect(remove).toBeDisabled();
  await review.getByLabel('Confirm workspace removal').fill('REMOVE WORKSPACE');
  for(const width of [1440,390]){
    await page.setViewportSize({width,height:1000});
    await review.scrollIntoViewIfNeeded();
    await page.screenshot({path:path.join(root,`workspace-review-${width}.png`),fullPage:true});
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
  }
  await remove.click();
  await expect(storage.getByText('Private workspace removal is verified. Imported notes and task receipts remain.',{exact:true})).toBeVisible();
  await expect(storage.getByText('No private research workspaces are retained.',{exact:true})).toBeVisible();
  const after=await page.evaluate(async()=>(await fetch('/api/export')).json());
  expect(after.runs[0].research.workerRetained).toBe(false);
  expect(after.runs[0].state).toBe('succeeded');
  expect(after.pages.find((entry:any)=>entry.path==='plans/summary.md').content).toContain('Audience: Developers');
  expect(fs.existsSync(path.join(root,'qemu-'+exported.runs[0].execution.sandboxId))).toBe(false);
  fs.writeFileSync(path.join(root,'browser-export-after-removal.json'),JSON.stringify(after,null,2));
  await page.reload(); await page.getByRole('button',{name:'Settings',exact:true}).click();
  await expect(storage.getByText('No private research workspaces are retained.',{exact:true})).toBeVisible();
  fs.writeFileSync(path.join(root,'browser-finished.json'),JSON.stringify({passed:true,syntheticModel:true}));
});
