import {test,expect} from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';
import {chooseMessageMode,navigateStudy,openSettings} from './navigation';

test('public search has separate credentials and an explicit per-task grant without dispatch during setup',async({page})=>{
 const key='fictional-browser-search-key';
 await page.goto('/');
 await page.getByLabel('Host access key',{exact:true}).fill(fs.readFileSync(path.resolve(process.env.THADDEUS_TEST_DATA||'../.data','host-key.txt'),'utf8').trim());
 await page.getByRole('button',{name:'Open workspace',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Conversation',exact:true})).toBeVisible();
 const before=await page.evaluate(async()=>(await fetch('/api/state')).json());
 await openSettings(page);
 const panel=page.getByRole('region',{name:'Public search connection',exact:true});
 await expect(panel.getByText('No available search key.',{exact:false})).toBeVisible();
 await expect(panel.getByLabel('Monthly search limit',{exact:true})).toHaveValue('100');
 await expect(panel.getByText('0 of 100 requests used',{exact:false})).toBeVisible();
 await panel.getByLabel('Monthly search limit',{exact:true}).fill('0');
 await panel.getByRole('button',{name:'Save search limit',exact:true}).click();
 await expect(panel.getByText('Saved: 0 searches per month. No search was sent.',{exact:true})).toBeVisible();
 await page.reload();
 await openSettings(page);
 await expect(panel.getByLabel('Monthly search limit',{exact:true})).toHaveValue('0');
 await panel.getByLabel('Monthly search limit',{exact:true}).fill('25');
 await panel.getByRole('button',{name:'Save search limit',exact:true}).click();
 await expect(panel.getByText('0 of 25 requests used',{exact:false})).toBeVisible();
 await panel.getByLabel('Search key storage',{exact:true}).selectOption('session');
 await panel.getByLabel('Search plan',{exact:true}).selectOption('retained');
 await panel.getByLabel('Brave Search API key',{exact:true}).fill(key);
 const save=panel.getByRole('button',{name:'Save search settings',exact:true});
 await expect(save).toBeEnabled();
 await save.click();
 await expect(panel.getByText('Search settings saved. No provider request was made.',{exact:true})).toBeVisible();
 await expect(panel.getByLabel('Brave Search API key',{exact:true})).toHaveValue('');
 await panel.getByRole('button',{name:'Check saved search key',exact:true}).click();
 await expect(panel.getByText('The host can read the saved search key.',{exact:false})).toBeVisible();
 const after=await page.evaluate(async()=>(await fetch('/api/state')).json());
 expect(after.search.configured).toBe(true);expect(after.search.providerVerified).toBe(false);
 expect(after.search.budget.monthlyLimit).toBe(25);expect(after.search.budget.used).toBe(0);
 expect(after.provider).toEqual(before.provider);expect(after.runs).toEqual(before.runs);expect(after.chats).toEqual(before.chats);
 const exported=await page.evaluate(async()=>(await fetch('/api/export')).text());expect(exported).not.toContain(key);
 expect(await page.evaluate(()=>JSON.stringify({local:{...localStorage},session:{...sessionStorage}}))).not.toContain(key);
 await navigateStudy(page,'Chat');
 await chooseMessageMode(page,'research');
 const scope=page.getByRole('region',{name:'Research scope',exact:true});
 const search=scope.getByRole('checkbox',{name:'Search the public web with Brave',exact:true});
 await expect(search).not.toBeChecked();await search.check();
 await expect(scope.getByText('Monthly search allowance: 0 / 25 used',{exact:false})).toBeVisible();
 await scope.getByLabel('Search request allowance',{exact:true}).selectOption('2');
 await scope.getByRole('checkbox',{name:'Allow opening the returned result pages',exact:true}).uncheck();
 const images=path.resolve(process.env.THADDEUS_SCREENSHOTS||'../artifacts/screenshots');fs.mkdirSync(images,{recursive:true});
 for(const width of [1440,390]){
  await page.setViewportSize({width,height:1000});await scope.scrollIntoViewIfNeeded();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await scope.screenshot({path:path.join(images,`search-scope-${width}.png`)});
 }
 await openSettings(page);
 for(const width of [1440,390]){
  await page.setViewportSize({width,height:1000});await panel.scrollIntoViewIfNeeded();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await panel.screenshot({path:path.join(images,`search-connection-${width}.png`)});
 }
 await panel.getByRole('button',{name:'Remove search key',exact:true}).click();
 await expect(panel.getByText('Search key removed.',{exact:true})).toBeVisible();
 await panel.getByRole('button',{name:'Check saved search key',exact:true}).click();
 await expect(panel.getByRole('alert')).toContainText('missing or unavailable');
 await navigateStudy(page,'Chat');
 await expect(page.getByRole('button',{name:'Start research',exact:true})).toBeDisabled();
 await page.reload();await chooseMessageMode(page,'research');
 await expect(search).not.toBeChecked();await expect(search).toBeDisabled();
 const final=await page.evaluate(async()=>(await fetch('/api/state')).json());
 expect(final.search.configured).toBe(false);expect(final.runs).toEqual(before.runs);expect(final.chats).toEqual(before.chats);
});
