import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import Markdown from 'react-markdown';
import { Home, ListTodo, Clock3, BookOpen, Settings, ArrowUpRight, ArrowUp, Plus, Check, ShieldCheck, ChevronRight, X, Feather, CircleAlert, WifiOff, FileText, Ban, LoaderCircle, PanelRightClose } from 'lucide-react';
import './style.css';

type Page = {path:string;content:string;version:string;updated:string};
type Provider = {kind:string;model:string;reasoning:string;endpoint?:string};
type Run = {id:string;state:string;summary:string;created:string;updated:string;goal:{objective:string;readScope:string[];provider:Provider;limits:Record<string,number>;criteria:{description:string;status:string}[]};approval?:{id:string;digest:string;action:{name:string;path:string;content:string};expires:string;decision:string};evidence:{path:string;hash:string;content:string}[];modelCalls:number;toolCalls:number;repairs:number;inputTokens?:number;outputTokens?:number;validation?:{checks:string[];unverified:string[]};outputPath?:string};
type State = {runs:Run[];pages:Page[];chats:{id:string;role:string;content:string}[];provider:Provider;writes:string;phoneOrigin?:string};
let csrf = '';
async function api<T=any>(path:string, body?:unknown, method='POST'):Promise<T> {
  const response = await fetch('/api'+path, body === undefined ? {cache:'no-store'} : {method,headers:{'Content-Type':'application/json','X-CSRF':csrf},body:JSON.stringify(body)});
  if (!response.ok) { const data = await response.json().catch(()=>({})); throw new Error(data.error || (response.status===401?'Session expired. Unlock the study again.':`Request failed (${response.status}). Refresh and try again.`)); }
  const text = await response.text(); return (text ? JSON.parse(text) : null) as T;
}
const names:Record<string,string> = {queued:'Queued',running:'Working',awaitingApproval:'Needs approval',succeeded:'Write verified',failed:'Failed',denied:'Denied',cancelled:'Cancelled',needsAttention:'Needs attention',paused:'Paused'};
function StateIcon({state}:{state:string}) { const Icon = state==='succeeded'?Check:state==='awaitingApproval'?ShieldCheck:state==='running'?LoaderCircle:state==='denied'||state==='cancelled'?Ban:state==='failed'||state==='needsAttention'?CircleAlert:Clock3; return <Icon size={18}/>; }
function Raven({state='idle',onClick}:{state?:string;onClick?:()=>void}) {
  return <button className={'raven '+state} onClick={onClick} aria-label={'Thaddeus raven: '+(names[state]||state)} title={names[state]||state}>
    <svg viewBox="0 0 48 48" shapeRendering="crispEdges" aria-hidden="true"><path fill="#11191e" d="M18 9h13v3h5v4h4v5h-8v14h-5v4H14v-4H9v-9h4V15h5z"/><path fill="#465767" d="M18 12h11v3h5v6h-7v12h-6v3h-7V23h4z"/><path fill="#283843" d="M14 25h8v4h5v6h-8v3h-9v-5H6v-4h8z"/><path fill="#8496a1" d="M18 14h3v7h-3zm4-2h7v3h-7z"/><path fill="#d7bb76" d="M34 16h9v3h-9zm-19 22h3v5h-6v-2h3zm10 0h3v3h4v2h-7z"/><path className="eye" fill="#eee6c7" d="M28 15h3v3h-3z"/><path fill="#758f83" d="M6 44h33v2H6z"/></svg>
  </button>;
}
function App() {
  const [session,setSession]=useState<{owner:boolean}|null>(null),[loaded,setLoaded]=useState(false),[key,setKey]=useState(''),[pair,setPair]=useState(false);
  const [data,setData]=useState<State|null>(null),[tab,setTab]=useState('Home'),[selected,setSelected]=useState<string|null>(null),[online,setOnline]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const [message,setMessage]=useState(''),[scope,setScope]=useState<string[]>([]),[fault,setFault]=useState(false),[showScope,setShowScope]=useState(false);
  const [page,setPage]=useState<Page|null>(null),[edit,setEdit]=useState(''),[revisions,setRevisions]=useState<Page[]>([]),[trace,setTrace]=useState<any[]>([]),[rail,setRail]=useState(true);
  const [provider,setProvider]=useState<Provider>({kind:'scripted',model:'fictional-weekly-v1',reasoning:'high'}),[diagnostic,setDiagnostic]=useState(''),[devices,setDevices]=useState<any>({devices:[],pending:[]}),[pairCode,setPairCode]=useState('');
  const [deleteText,setDeleteText]=useState('');
  async function refresh() { const state=await api<State>('/state'); setData(state); return state; }
  async function act(work:()=>Promise<unknown>) { setBusy(true);setError('');try {await work();await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);} }
  useEffect(()=>{api('/session').then(s=>{csrf=s.csrf;setSession(s);}).catch(()=>{}).finally(()=>setLoaded(true));},[]);
  useEffect(()=>{
    if(!session)return;
    refresh().then(d=>{setProvider(d.provider);setScope(d.pages.filter(p=>p.path.startsWith('notes/')).map(p=>p.path));}).catch(e=>setError(e.message));
    const events=new EventSource('/api/events');let timer:ReturnType<typeof setTimeout>|undefined;
    const offline=()=>setOnline(false);const reconnect=()=>api('/session').then(()=>{setOnline(true);return refresh();}).catch(()=>setOnline(false));
    window.addEventListener('offline',offline);window.addEventListener('online',reconnect);
    events.onopen=()=>setOnline(true);events.onerror=()=>setOnline(false);events.onmessage=()=>{clearTimeout(timer);timer=setTimeout(()=>refresh().catch(()=>setOnline(false)),80);};
    return()=>{events.close();clearTimeout(timer);window.removeEventListener('offline',offline);window.removeEventListener('online',reconnect);};
  },[session]);
  useEffect(()=>{if(selected)api('/runs/'+selected+'/replay').then(setTrace).catch(e=>setError(e.message));},[selected,data?.runs.find(r=>r.id===selected)?.updated]);
  useEffect(()=>{if(tab==='Settings'&&session?.owner)api('/devices').then(setDevices).catch(e=>setError(e.message));},[tab,data,session]);
  const run=data?.runs.find(r=>r.id===selected);
  const pending=data?.runs.filter(r=>r.state==='awaitingApproval')||[];
  const active=data?.runs.find(r=>['running','queued','awaitingApproval','needsAttention'].includes(r.state));
  const ravenState=!online?'disconnected':active?.state||'idle';
  async function openPage(path:string){const p=await api<Page>('/knowledge?path='+encodeURIComponent(path));setPage(p);setEdit(p.content);setRevisions(await api('/revisions?path='+encodeURIComponent(path)));setTab('Knowledge');setSelected(null);}
  async function seed(){await api('/demo/seed',{});await refresh();setScope(['notes/deadlines.md','notes/constraints.md','notes/conflict.md']);setShowScope(true);}
  async function start(){const r=await api<Run>('/runs',{objective:message||'Turn my scattered notes into a useful weekly plan.',readScope:scope,demoFailure:fault});setSelected(r.id);setTab('Tasks');setMessage('');setShowScope(false);}
  async function decision(allow:boolean){if(!run?.approval)return;await api('/runs/'+run.id+'/approve',{approvalId:run.approval.id,digest:run.approval.digest,allow});}
  function nav(name:string){setTab(name);setSelected(null);}
  function ledger(items:Run[]){let previous='';return items.map(r=>{const date=new Date(r.created);const today=new Date();const yesterday=new Date();yesterday.setDate(today.getDate()-1);const group=date.toDateString()===today.toDateString()?'Today':date.toDateString()===yesterday.toDateString()?'Yesterday':date.toLocaleDateString(undefined,{month:'long',day:'numeric'});const heading=group!==previous;previous=group;return <React.Fragment key={r.id}>{heading&&<h3 className="time-group">{group}</h3>}<button data-run-id={r.id} className="ledger-row" onClick={()=>{setSelected(r.id);setTab('Activity');}}><span className={'state-icon '+r.state}><StateIcon state={r.state}/></span><span className="ledger-copy"><strong>{r.goal.objective}</strong><small>{r.summary}</small></span><span className="ledger-time"><span className={'badge '+r.state}>{names[r.state]}</span><time>{date.toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit'})}</time></span><ChevronRight size={16}/></button></React.Fragment>;});}
  if(!loaded)return <main className="unlock"><Raven/><h1>Opening the study…</h1></main>;
  if(!session)return <main className="unlock"><div className="wordmark"><span className="mark">T</span>THADDEUS</div><Raven state="listening"/><p className="eyebrow">YOUR PRIVATE STUDY</p><h1>A little order.<br/><em>Entirely yours.</em></h1><p>Unlock this browser with the host access key.<br/>Your notes remain on the computer running Thaddeus.</p><form onSubmit={e=>{e.preventDefault();setError('');(pair?api('/pair/claim',{code:key,name:'Phone browser'}):api('/auth/login',{key})).then(s=>{if(pair){setError('Waiting for confirmation on the host. Then select Finish pairing.');}else{csrf=s.csrf;setSession(s);setKey('');}}).catch(e=>setError(e.message));}}><label>{pair?'One-time pairing code':'Host access key'}<input type="password" autoComplete="off" value={key} onChange={e=>setKey(e.target.value)} required/></label><button className="primary">{pair?'Request pairing':'Unlock study'} <ArrowUpRight size={17}/></button></form><button className="text-button" onClick={()=>setPair(!pair)}>{pair?'Use host access key':'Connect a phone instead'}</button>{pair&&<button onClick={()=>api('/pair/exchange',{}).then(s=>{if(s){csrf=s.csrf;setSession(s);}else setError('Host confirmation is still pending.');}).catch(e=>setError(e.message))}>Finish pairing</button>}<small>Host key: <code>.data/host-key.txt</code><br/>Phone access requires your host’s trusted HTTPS address.</small>{error&&<p role="alert" className="error">{error}</p>}</main>;
  return <div className="app"><aside className="sidebar"><button className="wordmark" onClick={()=>nav('Home')}><span className="mark">T</span><span>THADDEUS<small>A PRIVATE STUDY</small></span></button><button className="new-task" onClick={()=>{nav('Home');setShowScope(true);}}><Plus size={17}/> New intention</button><nav>{[[Home,'Home'],[ListTodo,'Tasks'],[Clock3,'Activity'],[BookOpen,'Knowledge'],[Settings,'Settings']].map(([Icon,name]:any)=><button key={name} aria-label={name} className={tab===name?'active':''} onClick={()=>nav(name)}><Icon size={19}/><span>{name}</span>{name==='Tasks'&&pending.length>0&&<b>{pending.length}</b>}</button>)}</nav><div className="sidebar-bottom"><div className="privacy"><ShieldCheck size={17}/><span>Private by design<small>Exact approval for every agent write</small></span></div><span className={'connection '+(!online?'offline':'')}>{online?'● Host connected':'○ Disconnected'}</span><small>The host must remain awake.</small></div></aside>
  <div className="workspace"><header><div className="breadcrumb">Your study <ChevronRight size={14}/><strong>{tab}</strong></div><div className="header-actions"><span className="mode-label">{data?.provider.kind==='scripted'?'SCRIPTED DEMO':'LIVE · '+data?.provider.model}</span>{pending.length>0&&<button className="approval-pill" onClick={()=>{setSelected(pending[0].id);setTab('Tasks');}}><ShieldCheck size={15}/>{pending.length} approval</button>}<span className="avatar">A</span></div></header>
  {!online&&<div role="status" className="disconnect"><WifiOff size={17}/> Connection lost. Writes and approvals are disabled until the host reconnects.</div>}
  {error&&<div className="error alert" role="alert">{error}<button aria-label="Dismiss error" onClick={()=>setError('')}><X size={16}/></button></div>}
  <main className={run?'main task-layout':'main'}>
  {run?<><section className="task-main"><button className="text-button" onClick={()=>setSelected(null)}>← Back to {tab.toLowerCase()}</button><p className="eyebrow">TASK RECEIPTS · {run.goal.provider.kind==='scripted'?'SIMULATED MODEL':'LIVE MODEL'}</p><h1>{run.goal.objective}</h1><div className="task-status"><span className={'badge '+run.state}><StateIcon state={run.state}/>{names[run.state]}</span><Raven state={online?run.state:'disconnected'}/></div><p className="lead">{run.summary}</p>
  {run.approval&&<section className="approval-card"><div className="card-heading"><ShieldCheck/><div><h2>{run.state==='awaitingApproval'?'Your permission, precisely.':'Write proposal'}</h2><p>{run.approval.action.name} · {run.approval.action.path}</p></div></div><p>This exact Markdown will be saved. No page write happens before approval.</p><div className="draft"><Markdown components={{a:({href,children})=>href && /^(notes|plans)\/[a-z0-9-]+\.md$/.test(href)?<button className="text-button" onClick={()=>act(()=>openPage(href))}>{children}</button>:<a href={href}>{children}</a>}}>{run.approval.action.content}</Markdown></div><details><summary>Exact arguments & approval binding</summary><pre>{JSON.stringify(run.approval,null,2)}</pre></details>{run.state==='awaitingApproval'&&<div className="approval-actions"><span>Expires {new Date(run.approval.expires).toLocaleTimeString()}</span><button disabled={busy||!online} onClick={()=>act(()=>decision(false))}>Deny write</button><button className="primary" disabled={busy||!online} onClick={()=>act(()=>decision(true))}><Check size={16}/> Approve exact write</button></div>}</section>}
  {run.outputPath&&<button className="primary" onClick={()=>act(()=>openPage(run.outputPath!))}>Open editable plan <ArrowUpRight size={16}/></button>}
  {['queued','running','awaitingApproval','paused'].includes(run.state)&&<button className="text-button" disabled={busy||!online} onClick={()=>act(()=>api('/runs/'+run.id+'/cancel',{}))}>Cancel task</button>}
  {run.state==='paused'&&<button disabled={busy||!online} onClick={()=>act(()=>api('/runs/'+run.id+'/resume',{}))}>Resume safe work</button>}
  <section className="receipt-block"><h2>What was checked</h2>{run.validation?.checks.map(c=><p key={c} className="check"><Check size={16}/>{c}</p>)}{(!run.validation||run.validation.unverified.length>0)&&<p className="muted">Factual accuracy and the conflict decision remain unverified. Structural checks are not a fact-check.</p>}</section>
  <details className="trace"><summary>Replay recorded events · {trace.length} receipts · no re-execution</summary>{trace.map(e=><details key={e.eventId}><summary>{e.sequence}. {e.type} · {new Date(e.timestamp).toLocaleTimeString()}</summary><pre>{JSON.stringify(e,null,2)}</pre></details>)}</details></section>
  <aside className={'evidence-rail '+(!rail?'collapsed':'')}><button className="text-button" onClick={()=>setRail(!rail)}><PanelRightClose size={16}/>{rail?'Collapse receipts':'Show receipts'}</button>{rail&&<><h3>Behind the outcome</h3><p className="eyebrow">SOURCE EVIDENCE</p>{run.evidence.map(e=><details key={e.path} className="source"><summary><FileText size={17}/>{e.path}</summary><pre>{e.content}</pre><small>SHA-256 {e.hash}</small></details>)}<p className="eyebrow">RUN SNAPSHOT</p><dl><dt>Provider</dt><dd>{run.goal.provider.kind}</dd><dt>Model</dt><dd>{run.goal.provider.model}</dd><dt>Reasoning</dt><dd>{run.goal.provider.reasoning}</dd><dt>Model calls</dt><dd>{run.modelCalls} / {run.goal.limits.modelCalls}</dd><dt>Tool calls</dt><dd>{run.toolCalls} / {run.goal.limits.toolCalls}</dd><dt>Repairs</dt><dd>{run.repairs}</dd><dt>Tokens in / out</dt><dd>{run.inputTokens??'unknown'} / {run.outputTokens??'unknown'}</dd><dt>Cost</dt><dd>Unknown</dd><dt>Elapsed to last event</dt><dd>{((+new Date(run.updated)-+new Date(run.created))/1000).toFixed(1)}s</dd></dl><small>Waiting for approval is included in wall time. No invented progress percentages.</small></>}</aside></>:
  tab==='Home'?<section className="home"><div className="welcome"><div><p className="eyebrow"><span/> A QUIETER KIND OF ASSISTANT</p><h1>Make room for<br/><em>what matters.</em></h1><p className="lead">Bring the scattered thoughts.<br/>We’ll find the next sensible step.</p></div><div className="raven-stage"><Raven state={ravenState} onClick={()=>active&&setSelected(active.id)}/><span>{active?names[active.state]:'At your service.'}</span></div></div>
  <div className="composer"><textarea aria-label="Message or goal" placeholder="What would you like to make sense of?" value={message} onChange={e=>setMessage(e.target.value)}/><div><span><Feather size={14}/> {data?.provider.kind==='scripted'?'Scripted demo · no model calls':'Selected notes go to '+data?.provider.endpoint}</span><button aria-label="Send message" disabled={!message||busy||!online} onClick={()=>act(async()=>{await api('/chat',{content:message});setMessage('');})}><ArrowUp size={18}/></button></div></div>
  <div className="suggestions"><button onClick={()=>act(seed)}><BookOpen size={16}/> Try the fictional weekly plan <ArrowUpRight size={14}/></button><button onClick={()=>setShowScope(!showScope)}><Plus size={16}/> Create a plan from my notes</button></div>
  {showScope&&<section className="scope-card"><h2>A small, explicit workspace</h2><p>Allow reading only these notes. The next write will need a separate approval.</p>{data?.pages.filter(p=>p.path.startsWith('notes/')).map(p=><label className="checkbox" key={p.path}><input type="checkbox" checked={scope.includes(p.path)} onChange={e=>setScope(e.target.checked?[...scope,p.path]:scope.filter(s=>s!==p.path))}/>{p.path}</label>)}{!data?.pages.length&&<button onClick={()=>act(seed)}>Load fictional notes</button>}<label className="checkbox"><input type="checkbox" checked={fault} onChange={e=>setFault(e.target.checked)}/> Demo only: exercise one bounded draft repair</label><button className="primary" disabled={!scope.length||busy||!online} onClick={()=>act(start)}>Read selected notes & create a plan <ArrowUpRight size={16}/></button></section>}
  {data?.chats.map(c=><div key={c.id} className={'chat '+c.role}><small>{c.role==='user'?'YOU':'THADDEUS · DETERMINISTIC CONVERSATION'}</small><p>{c.content}</p></div>)}
  <div className="section-heading"><h2>On your mind</h2><button className="text-button" onClick={()=>nav('Tasks')}>All tasks <ArrowUpRight size={14}/></button></div>{data?.runs.length?ledger(data.runs.slice(0,3)):<div className="empty"><span className="empty-icon"><Feather size={24}/></span><div><h3>A clean page is a fine beginning.</h3><p>Start with a weekly plan. Three fictional notes, one honest conflict,<br className="desktop-only"/> and nothing saved without your say-so.</p></div></div>}
  <div className="home-foot"><ShieldCheck size={17}/><p>Your host. Your notes. Your final say.<small>Inspect the evidence behind every consequential action.</small></p></div></section>:
  tab==='Activity'||tab==='Tasks'?<section className="listing"><p className="eyebrow">{tab==='Activity'?'THE WORK, WITH RECEIPTS':'INTENTIONS INTO OUTCOMES'}</p><h1>{tab==='Activity'?'A record worth keeping.':'One thing at a time.'}</h1><p className="lead">{tab==='Activity'?'What happened, what changed, and what still needs you.':'Clear objectives. Visible boundaries. Honest stopping points.'}</p>{data?.runs.length?ledger(data.runs):<div className="empty"><Clock3/><p>No tasks yet. A remarkably well-behaved history.</p></div>}</section>:
  tab==='Knowledge'?<section className="knowledge"><p className="eyebrow">THOUGHTS, KEPT CLOSE</p><h1>{page?page.path.split('/')[1].replace('.md','').replaceAll('-',' '):'Your working notebook.'}</h1><div className="knowledge-grid"><div className="page-list"><button onClick={()=>{setPage({path:'notes/new-note.md',content:'',version:'absent',updated:''});setEdit('');setRevisions([]);}}><Plus size={16}/> New note</button>{data?.pages.map(p=><button className={page?.path===p.path?'active':''} key={p.path} onClick={()=>act(()=>openPage(p.path))}><FileText size={16}/>{p.path}</button>)}</div>{page?<div className="editor"><label>Page path<input disabled={page.version!=='absent'} value={page.path} onChange={e=>setPage({...page,path:e.target.value})}/></label><label>Markdown<textarea aria-label="Markdown editor" value={edit} onChange={e=>setEdit(e.target.value)}/></label><button className="primary" disabled={busy||!online} onClick={()=>act(async()=>{const p=await api<Page>('/knowledge',{path:page.path,content:edit,version:page.version},'PUT');setPage(p);setRevisions(await api('/revisions?path='+encodeURIComponent(p.path)));})}>Save my edits <Check size={16}/></button><details><summary>Reading view</summary><div className="draft"><Markdown components={{a:({href,children})=>href && /^(notes|plans)\/[a-z0-9-]+\.md$/.test(href)?<button className="text-button" onClick={()=>act(()=>openPage(href))}>{children}</button>:<a href={href}>{children}</a>}}>{edit}</Markdown></div></details><details><summary>Revision history · {revisions.length}</summary>{revisions.map((p,i)=><details key={i}><summary>{new Date(p.updated).toLocaleString()} · {p.version.slice(0,12)}</summary><pre>{p.content}</pre></details>)}</details></div>:<div className="empty"><BookOpen/><p>Choose a page or start a note.<br/>Your words are stored as ordinary Markdown.</p></div>}</div></section>:
  <section className="settings"><p className="eyebrow">BOUNDARIES MAKE GOOD COMPANIONS</p><h1>Settle into your study.</h1>{!session.owner?<p>Provider, device, and data settings are managed on the host.</p>:<><section><h2>Model & destination</h2><p>Scripted mode is offline. A compatible endpoint receives selected source notes. No automatic fallback.</p><label>Provider<select value={provider.kind} onChange={e=>setProvider({...provider,kind:e.target.value})}><option value="scripted">Scripted demo · simulated</option><option value="compatible">OpenAI-compatible endpoint</option></select></label><label>Exact model ID<input value={provider.model} onChange={e=>setProvider({...provider,model:e.target.value})}/></label>{provider.kind==='compatible'&&<label>Base endpoint (ending in /v1)<input value={provider.endpoint||''} onChange={e=>setProvider({...provider,endpoint:e.target.value})}/></label>}<label>Reasoning<select value={provider.reasoning} onChange={e=>setProvider({...provider,reasoning:e.target.value})}><option>high</option><option>medium</option><option>low</option></select></label><p className="muted">Credentials: server environment Thaddeus__ApiKey. Glimmer: unconfigured; no model ID or capability assumed.</p><button disabled={busy||!online} className="primary" onClick={()=>act(()=>api('/settings/provider',provider,'PUT'))}>Save provider & destination</button><button disabled={busy||!online} onClick={()=>act(async()=>setDiagnostic(JSON.stringify(await api('/settings/test',{}))))}>Test saved provider</button>{diagnostic&&<p role="status">{diagnostic}</p>}</section>
  <section><h2>Agent permissions</h2><label>Knowledge writes<select value={data?.writes||'ask'} onChange={e=>act(()=>api('/settings/permissions',{writes:e.target.value},'PUT'))}><option value="ask">Ask · exact single-action approval</option><option value="off">Off</option></select></label><p>Reading is scoped when you start a goal. Always-write is intentionally unavailable in this milestone.</p></section>
  <section><h2>Your devices</h2><p>{data?.phoneOrigin?'Phone address: '+data.phoneOrigin:'Phone HTTPS is not configured.'} A phone connects to this host, not its own localhost. The host must remain awake. Physical-device setup is unverified.</p><button disabled={busy||!online||!data?.phoneOrigin} onClick={()=>act(async()=>setPairCode((await api('/pair/start',{})).code))}>Create one-time pairing code</button>{pairCode&&<p className="pair-code">{pairCode} · expires in 5 minutes</p>}{devices.pending.map((p:any)=><div key={p.id}><span>{p.name} requests access</span><button onClick={()=>act(()=>api('/pair/'+p.id+'/confirm',{}))}>Confirm this device</button></div>)}{devices.devices.map((d:any)=><div className="device" key={d.id}><span>{d.name}<small>Expires {new Date(d.expires).toLocaleDateString()}</small></span><button onClick={()=>act(()=>api('/devices/'+d.id+'/revoke',{}))}>Revoke</button></div>)}</section>
  <section><h2>Your data, your exit</h2><a className="button" href="/api/export" download>Export notes & receipts</a><label>Delete all notes, runs, chats & revisions<input placeholder="Type DELETE MY DATA" value={deleteText} onChange={e=>setDeleteText(e.target.value)}/></label><button disabled={deleteText!=='DELETE MY DATA'||!online||busy} onClick={()=>act(async()=>{await api('/data/delete',{confirmation:deleteText});setDeleteText('');setPage(null);})}>Delete my data</button><p>Storage is local and not application-encrypted. Deletion is not a secure disk erase. Sessions and provider settings remain.</p></section></>}<section><h2>Take the study with you</h2><p>On a supported browser, use “Install app” or “Add to Home Screen.” Trusted HTTPS is required for phone installation. Only the static shell is cached; private API data is not. Offline writes are never queued.</p></section></section>}
  </main><footer><span>THADDEUS / 02</span><span>A little order. No sleight of hand.</span></footer></div></div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
if('serviceWorker' in navigator) navigator.serviceWorker.register('/sw.js').catch(()=>{});
