import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import Markdown from 'react-markdown';
import { Home, ListTodo, Clock3, BookOpen, Settings, ArrowUpRight, ArrowUp, Plus, Check, ShieldCheck, ChevronRight, X, Feather, CircleAlert, WifiOff, FileText, Ban, LoaderCircle, PanelRightClose } from 'lucide-react';
import './style.css';
import './workspace.css';
import {Collections} from './components/Collections';
import {StudySearch} from './components/StudySearch';
import {MessageSquare, Lightbulb, Rss, Search, PanelRightOpen} from 'lucide-react';
import {api,setCsrf,readReplay,restoreSession} from './api';
import type {Page,Provider,Run,State} from './types';
import {names,StateIcon,Raven} from './components/Raven';
import {Conversation} from './components/Conversation';
import {TaskDetail} from './components/TaskDetail';
import {BudgetFields,defaultLimits} from './components/BudgetFields';
import {SandboxSettings} from './components/SandboxSettings';
import {HostWorkerSettings} from './components/HostWorkerSettings';
import {ResearchScope} from './components/ResearchScope';
import {TokenUsage} from './components/TokenUsage';
import {WorkspaceSettings} from './components/WorkspaceSettings';
import {MemoryNotebook} from './components/MemoryNotebook';
import type {MemorySelection} from './types';

function App() {
  const [session,setSession]=useState<{owner:boolean}|null>(null),[loaded,setLoaded]=useState(false),[key,setKey]=useState(''),[pair,setPair]=useState(false);
  const [data,setData]=useState<State|null>(null),[tab,setTab]=useState('Home'),[selected,setSelected]=useState<string|null>(null),[online,setOnline]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const [message,setMessage]=useState(''),[scope,setScope]=useState<string[]>([]),[fault,setFault]=useState(false),[showScope,setShowScope]=useState(false);
  const [page,setPage]=useState<Page|null>(null),[edit,setEdit]=useState(''),[revisions,setRevisions]=useState<Page[]>([]),[trace,setTrace]=useState<any[]>([]);
  const [provider,setProvider]=useState<Provider>({kind:'scripted',model:'fictional-weekly-v1',reasoning:'high'}),[diagnostic,setDiagnostic]=useState(''),[devices,setDevices]=useState<any>({devices:[],pending:[]}),[pairCode,setPairCode]=useState('');
  const [deleteText,setDeleteText]=useState('');
  const [limits,setLimits]=useState(defaultLimits);
  const [chatLimits,setChatLimits]=useState({...defaultLimits,modelCalls:1,toolCalls:0,repairs:0});
  const [mode,setMode]=useState('chat'),[hosts,setHosts]=useState('');
  const [memoryScope,setMemoryScope]=useState<MemorySelection[]>([]);
  const [focusId,setFocusId]=useState<string|undefined>();
  const [logOpen,setLogOpen]=useState(()=>window.innerWidth>1100);
  const [researchLimits,setResearchLimits]=useState({...defaultLimits,modelCalls:6,toolCalls:16,seconds:600,maxTotalTokens:96000});
  useEffect(()=>{const small=window.matchMedia('(max-width:1100px)');const changed=()=>{if(small.matches)setLogOpen(false);};small.addEventListener('change',changed);return()=>small.removeEventListener('change',changed);},[]);
  async function refresh() { const state=await api<State>('/state'); setData(state); return state; }
  async function act(work:()=>Promise<unknown>) { setBusy(true);setError('');try {await work();await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);} }
  useEffect(()=>{
    let stale=false;
    const restore=()=>restoreSession().then(s=>{if(!stale&&s){setCsrf(s.csrf);setSession(s);setError('');}}).catch(e=>{if(!stale)setError(e.message);}).finally(()=>{if(!stale)setLoaded(true);});
    const launch=()=>{if(new URLSearchParams(location.hash.slice(1)).has('launch'))void restore();};
    void restore();window.addEventListener('hashchange',launch);
    return()=>{stale=true;window.removeEventListener('hashchange',launch);};
  },[]);
  useEffect(()=>{
    if(!session)return;
    refresh().then(d=>{setProvider(d.provider);setScope(d.pages.filter(p=>p.path.startsWith('notes/')).map(p=>p.path));}).catch(e=>setError(e.message));
    const events=new EventSource('/api/events');let timer:ReturnType<typeof setTimeout>|undefined;
    const offline=()=>setOnline(false);const reconnect=()=>api('/session').then(()=>{setOnline(true);return refresh();}).catch(()=>setOnline(false));
    window.addEventListener('offline',offline);window.addEventListener('online',reconnect);
    events.onopen=()=>{setOnline(true);refresh().catch(()=>setOnline(false));};events.onerror=()=>setOnline(false);events.onmessage=()=>{clearTimeout(timer);timer=setTimeout(()=>refresh().catch(()=>setOnline(false)),80);};
    return()=>{events.close();clearTimeout(timer);window.removeEventListener('offline',offline);window.removeEventListener('online',reconnect);};
  },[session]);
  useEffect(()=>{let stale=false;setTrace([]);if(selected)readReplay(selected,()=>stale).then(events=>{if(!stale)setTrace(events);}).catch(e=>{if(!stale)setError(e.message);});return()=>{stale=true;};},[selected,data?.runs.find(r=>r.id===selected)?.updated]);
  useEffect(()=>{if(tab==='Settings'&&session?.owner)api('/devices').then(setDevices).catch(e=>setError(e.message));},[tab,data,session]);
  const run=data?.runs.find(r=>r.id===selected);
  const pending=data?.runs.filter(r=>r.state==='awaitingApproval')||[];
  const active=data?.runs.find(r=>['running','queued','awaitingApproval','awaitingInput','needsAttention'].includes(r.state));
  const ravenState=!online?'disconnected':active?.state||'idle';
  async function openPage(path:string){const p=await api<Page>('/knowledge?path='+encodeURIComponent(path));setPage(p);setEdit(p.content);setRevisions(await api('/revisions?path='+encodeURIComponent(path)));setTab('Knowledge');setSelected(null);}
  async function seed(){await api('/demo/seed',{});await refresh();setScope(['notes/deadlines.md','notes/constraints.md','notes/conflict.md']);setShowScope(true);}
  async function start(){const r=await api<Run>('/runs',{objective:message||'Turn my scattered notes into a useful weekly plan.',readScope:scope,demoFailure:fault,budget:limits});showRun(r.id);setMessage('');setShowScope(false);}
  async function sendMessage(){
    const payload=mode==='research'?{content:message,mode,readScope:scope,memories:memoryScope,budget:researchLimits,web:hosts.trim()?{hosts:hosts.split(',').map(host=>host.trim().toLowerCase()).filter(Boolean),maxFetches:4}:null}:{content:message,budget:chatLimits};
    const created=await api<Run>('/chat',payload);setMessage('');setFocusId(undefined);
    if(mode==='research'){showRun(created.id);}
  }
  async function decision(allow:boolean){if(!run?.approval)return;await api('/runs/'+run.id+'/approve',{approvalId:run.approval.id,digest:run.approval.digest,allow});}
  function nav(name:string){setFocusId(undefined);setTab(name);setSelected(null);if(window.innerWidth<=1100)setLogOpen(false);}
  function showRun(id:string){setSelected(id);setTab('Activity');if(window.innerWidth<=1100)setLogOpen(false);}
  function discuss(text:string){nav('Home');setMessage(text);setMode('chat');requestAnimationFrame(()=>document.querySelector<HTMLTextAreaElement>('[aria-label="Message or goal"]')?.focus());}
  useEffect(()=>{const escape=(event:KeyboardEvent)=>{if(event.key==='Escape'&&logOpen){setLogOpen(false);document.querySelector<HTMLButtonElement>('[aria-label="Activity log"]')?.focus();}};window.addEventListener('keydown',escape);return()=>window.removeEventListener('keydown',escape);},[logOpen]);
  function ledger(items:Run[]){let previous='';return items.map(r=>{const date=new Date(r.created);const today=new Date();const yesterday=new Date();yesterday.setDate(today.getDate()-1);const group=date.toDateString()===today.toDateString()?'Today':date.toDateString()===yesterday.toDateString()?'Yesterday':date.toLocaleDateString(undefined,{month:'long',day:'numeric'});const heading=group!==previous;previous=group;return <React.Fragment key={r.id}>{heading&&<h3 className="time-group">{group}</h3>}<button data-run-id={r.id} className="ledger-row" onClick={()=>{showRun(r.id);}}><span className={'state-icon '+r.state}><StateIcon state={r.state}/></span><span className="ledger-copy"><strong>{r.goal.objective.length>80?r.goal.objective.slice(0,77)+'…':r.goal.objective}</strong><small>{r.summary}</small></span><span className="ledger-time"><span className={'badge '+r.state}>{names[r.state]}</span><time>{date.toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit'})}</time></span><ChevronRight size={16}/></button></React.Fragment>;});}
  if(!loaded)return <main className="unlock"><Raven/><h1>Opening the study…</h1></main>;
  if(!session)return <main className="unlock"><div className="wordmark"><span className="mark">T</span>THADDEUS</div><Raven state="listening"/><p className="eyebrow">YOUR PRIVATE STUDY</p><h1>A little order.<br/><em>Entirely yours.</em></h1><p>Unlock this browser with the host access key.<br/>Your notes remain on the computer running Thaddeus.</p><form onSubmit={e=>{e.preventDefault();setError('');(pair?api('/pair/claim',{code:key,name:'Phone browser'}):api('/auth/login',{key})).then(s=>{if(pair){setError('Waiting for confirmation on the host. Then select Finish pairing.');}else{setCsrf(s.csrf);setSession(s);setKey('');}}).catch(e=>setError(e.message));}}><label>{pair?'One-time pairing code':'Host access key'}<input type="password" autoComplete="off" value={key} onChange={e=>setKey(e.target.value)} required/></label><button className="primary">{pair?'Request pairing':'Unlock study'} <ArrowUpRight size={17}/></button></form><button className="text-button" onClick={()=>setPair(!pair)}>{pair?'Use host access key':'Connect a phone instead'}</button>{pair&&<button onClick={()=>api('/pair/exchange',{}).then(s=>{if(s){setCsrf(s.csrf);setSession(s);}else setError('Host confirmation is still pending.');}).catch(e=>setError(e.message))}>Finish pairing</button>}<small>Host key: <code>.data/host-key.txt</code><br/>Phone access requires your host’s trusted HTTPS address.</small>{error&&<p role="alert" className="error">{error}</p>}</main>;
  return <div className={'app study-shell '+(logOpen?'log-open':'')}>
  <div className="mobile-masthead"><Raven state={ravenState} onClick={()=>active&&showRun(active.id)}/><div><strong>Thaddeus</strong><small>{online?'At your service.':'Waiting for the host.'}</small></div><span className="edition">THE PRIVATE STUDY</span></div>
  <aside className="sidebar"><button className="wordmark" onClick={()=>nav('Home')}><span className="mark">T</span><span>THADDEUS<small>YOUR PRIVATE STUDY</small></span></button><p className="nav-caption">THE STUDY</p><nav aria-label="Study navigation">{[[MessageSquare,'Home','Conversation'],[FileText,'Knowledge','Artifacts'],[ListTodo,'Todo','To-do'],[Lightbulb,'Ideas','Ideas'],[Rss,'Feed','Feed'],[Search,'Search','Search'],[Settings,'Settings','Settings']].map(([Icon,name,label]:any)=><button key={name} aria-label={label} aria-current={tab===name&&!selected?'page':undefined} className={tab===name&&!selected?'active':''} onClick={()=>nav(name)}><Icon size={18}/><span>{label}</span>{name==='Todo'&&!!data?.library?.filter(item=>item.kind==='todo'&&item.status==='open').length&&<b>{data.library.filter(item=>item.kind==='todo'&&item.status==='open').length}</b>}</button>)}</nav><div className="sidebar-bottom"><div className="privacy"><ShieldCheck size={16}/><span>Yours to decide.<small>Review every agent write.</small></span></div><span className={'connection '+(!online?'offline':'')}>{online?'● Host connected':'○ Disconnected'}</span><small>The host must remain awake.</small></div></aside>
  <div className="workspace"><header><div className="breadcrumb"><span>Your study</span><ChevronRight size={13}/><strong>{selected?'Run details':({Home:'Conversation',Knowledge:'Artifacts',Todo:'To-do'} as Record<string,string>)[tab]||tab}</strong></div><div className="header-actions"><span className="mode-label">{data?.provider.kind==='scripted'?'SCRIPTED DEMO':data?.provider.model}</span>{pending.length>0&&<button className="approval-pill" onClick={()=>showRun(pending[0].id)}><ShieldCheck size={15}/>{pending.length} approval</button>}<button aria-label="Activity log" aria-expanded={logOpen} aria-controls="activity-log" className="log-toggle" onClick={()=>setLogOpen(!logOpen)}>{logOpen?<PanelRightClose size={18}/>:<PanelRightOpen size={18}/>}<span>Log</span></button></div></header>
  {!online&&<div role="status" className="disconnect"><WifiOff size={17}/> Connection lost. Writes and approvals are disabled until the host reconnects.</div>}
  {error&&<div className="error alert" role="alert">{error}<button aria-label="Dismiss error" onClick={()=>setError('')}><X size={16}/></button></div>}
  {data&&<TokenUsage runs={data.runs} onRun={showRun}/>}
  <main className={run?'main task-layout':'main'} aria-label="Workspace">
{run?<TaskDetail run={run} trace={trace} online={online} busy={busy} onBack={()=>nav('Home')} onPage={path=>act(()=>openPage(path))} onDecision={allow=>act(()=>decision(allow))} onCancel={()=>act(()=>api('/runs/'+run.id+'/cancel',{}))} onResume={()=>act(()=>api('/runs/'+run.id+'/resume',{}))} onReconcile={refresh}/>:
  tab==='Home'?<section className="home conversation-workspace"><div className="conversation-title"><p className="eyebrow">A LITTLE ORDER. ROOM FOR WONDER.</p><h1>Conversation</h1></div>
  {!data?.chats.length&&<div className="conversation-empty"><Feather size={26}/><h2>What shall we make of today?</h2><p>Bring a question, an idea, or a little unfinished business.</p></div>}
  <Conversation focusId={focusId} messages={data?.chats||[]} runs={data?.runs||[]} online={online} busy={busy} onCancel={id=>act(()=>api('/runs/'+id+'/cancel',{}))} onGoal={text=>{setMessage(text);setShowScope(true);}}/>
  {active&&active.goal.kind!=='conversation'&&<button className="active-work" onClick={()=>showRun(active.id)}><StateIcon state={active.state}/><span><strong>{names[active.state]}</strong><small>{active.goal.objective}</small></span><ArrowUpRight size={16}/></button>}
  <div className="conversation-compose">
  <div className="compose-options"><label>Message mode<select aria-label="Message mode" value={mode} onChange={e=>setMode(e.target.value)}><option value="chat">Chat</option><option value="research">Research with selected sources</option></select></label>
  </div>{mode==='research'&&<ResearchScope availability={data?.research} pages={data?.pages||[]} scope={scope} onScope={setScope} memories={data?.memories||[]} memoryScope={memoryScope} onMemories={setMemoryScope} hosts={hosts} onHosts={setHosts} limits={researchLimits} onLimits={setResearchLimits}/>}
  <p className="muted">Next {mode==='research'?'research task':'reply'}: {(mode==='research'?researchLimits:chatLimits).maxTotalTokens.toLocaleString()} token allowance · up to {(mode==='research'?researchLimits:chatLimits).maxOutputTokens.toLocaleString()} output tokens per call · {(mode==='research'?researchLimits:chatLimits).modelCalls} model call{(mode==='research'?researchLimits:chatLimits).modelCalls===1?'':'s'}.</p>
  {mode==='chat'&&<BudgetFields value={chatLimits} onChange={setChatLimits}/>}
  <div className="composer"><textarea aria-label="Message or goal" placeholder={mode==='research'?'What should I investigate? Include any source links.':'What would you like to make sense of?'} value={message} onChange={e=>setMessage(e.target.value)}/><div><span><Feather size={14}/> {mode==='research'?'Research uses your selected sources and model':data?.provider.kind==='scripted'?'Scripted demo · no model calls':'Messages and scoped notes go to '+data?.provider.endpoint}</span><button aria-label={mode==='research'?'Start research':'Send message'} disabled={!message.trim()||busy||!online||(mode==='research'?(!data?.research?.enabled||data?.provider.kind!=='compatible'||(!scope.length&&!hosts.trim()&&!memoryScope.length)||memoryScope.some(selection=>!data?.memories?.some(({entry,sourceStatus})=>entry.id===selection.id&&entry.version===selection.version&&sourceStatus==='current'))||data?.runs.some(r=>r.research&&r.research.phase!=='finished')):data?.runs.some(r=>r.goal.kind==='conversation'&&['queued','running'].includes(r.state)))} onClick={()=>act(sendMessage)}><ArrowUp size={18}/></button></div></div>
  {mode==='research'&&data?.provider.kind!=='compatible'&&<p role="status">Configure a compatible model in Settings before starting research.</p>}
  <div className="suggestions"><button onClick={()=>act(seed)}><BookOpen size={16}/> Try the fictional weekly plan <ArrowUpRight size={14}/></button><button onClick={()=>setShowScope(!showScope)}><Plus size={16}/> Create a plan from my notes</button></div>
  {showScope&&<section className="scope-card" aria-label="Plan scope"><h2>A small, explicit workspace</h2><p>Allow reading only these notes. The next write will need a separate approval.</p>{data?.pages.filter(p=>p.path.startsWith('notes/')).map(p=><label className="checkbox" key={p.path}><input type="checkbox" checked={scope.includes(p.path)} onChange={e=>setScope(e.target.checked?[...scope,p.path]:scope.filter(s=>s!==p.path))}/>{p.path}</label>)}{!data?.pages.length&&<button onClick={()=>act(seed)}>Load fictional notes</button>}<label className="checkbox"><input type="checkbox" checked={fault} onChange={e=>setFault(e.target.checked)}/> Demo only: exercise one bounded draft repair</label><BudgetFields value={limits} onChange={setLimits}/><button className="primary" disabled={!scope.length||busy||!online} onClick={()=>act(start)}>Read selected notes & create a plan <ArrowUpRight size={16}/></button></section>}
  </div></section>:
  tab==='Todo'||tab==='Ideas'||tab==='Feed'?<Collections key={tab+(focusId||'')} focusId={focusId} kind={tab==='Todo'?'todo':tab==='Ideas'?'idea':'feed'} items={data?.library||[]} online={online} onChanged={refresh} onDiscuss={discuss}/>:
  tab==='Search'&&data?<StudySearch data={data} onPage={path=>act(()=>openPage(path))} onRun={showRun} onCollection={(kind,id)=>{nav(kind==='todo'?'Todo':kind==='idea'?'Ideas':'Feed');setFocusId(id);}} onChat={id=>{nav('Home');setFocusId(id);}}/>:
  tab==='Knowledge'?<section className="knowledge"><p className="eyebrow">SAVED & SOURCE-LINKED</p><h1>{page?page.path.split('/')[1].replace('.md','').replaceAll('-',' '):'Artifacts'}</h1><MemoryNotebook memories={data?.memories||[]} pages={data?.pages||[]} online={online} onChanged={refresh} onOpen={path=>act(()=>openPage(path))}/><div className="knowledge-grid"><div className="page-list"><button onClick={()=>{setPage({path:'notes/new-note.md',content:'',version:'absent',updated:''});setEdit('');setRevisions([]);}}><Plus size={16}/> New note</button>{data?.pages.map(p=><button className={page?.path===p.path?'active':''} key={p.path} onClick={()=>act(()=>openPage(p.path))}><FileText size={16}/>{p.path}</button>)}</div>{page?<div className="editor"><label>Page path<input disabled={page.version!=='absent'} value={page.path} onChange={e=>setPage({...page,path:e.target.value})}/></label><label>Markdown<textarea aria-label="Markdown editor" value={edit} onChange={e=>setEdit(e.target.value)}/></label><button className="primary" disabled={busy||!online} onClick={()=>act(async()=>{const p=await api<Page>('/knowledge',{path:page.path,content:edit,version:page.version},'PUT');setPage(p);setRevisions(await api('/revisions?path='+encodeURIComponent(p.path)));})}>Save my edits <Check size={16}/></button><details><summary>Reading view</summary><div className="draft"><Markdown components={{a:({href,children})=>href && /^(notes|plans)\/[a-z0-9-]+\.md$/.test(href)?<button className="text-button" onClick={()=>act(()=>openPage(href))}>{children}</button>:<a href={href}>{children}</a>}}>{edit}</Markdown></div></details><details><summary>Revision history · {revisions.length}</summary>{revisions.map((p,i)=><details key={i}><summary>{new Date(p.updated).toLocaleString()} · {p.version.slice(0,12)}</summary><pre>{p.content}</pre></details>)}</details></div>:<div className="empty"><BookOpen/><p>Choose a page or start a note.<br/>Your words are stored as ordinary Markdown.</p></div>}</div></section>:
  <section className="settings"><p className="eyebrow">BOUNDARIES MAKE GOOD COMPANIONS</p><h1>Settings</h1>{!session.owner?<p>Provider, device, and data settings are managed on the host.</p>:<><section><h2>Model & destination</h2><p>Scripted mode is offline. A compatible endpoint receives selected source notes. No automatic fallback.</p><label>Provider<select value={provider.kind} onChange={e=>setProvider({...provider,kind:e.target.value})}><option value="scripted">Scripted demo · simulated</option><option value="compatible">OpenAI-compatible endpoint</option></select></label><label>Exact model ID<input value={provider.model} onChange={e=>setProvider({...provider,model:e.target.value})}/></label>{provider.kind==='compatible'&&<label>Base endpoint (ending in /v1)<input value={provider.endpoint||''} onChange={e=>setProvider({...provider,endpoint:e.target.value})}/></label>}<label>Reasoning<select value={provider.reasoning} onChange={e=>setProvider({...provider,reasoning:e.target.value})}><option>high</option><option>medium</option><option>low</option></select></label><p className="muted">Credentials: server environment Thaddeus__ApiKey. Glimmer: unconfigured; no model ID or capability assumed.</p><button disabled={busy||!online} className="primary" onClick={()=>act(()=>api('/settings/provider',provider,'PUT'))}>Save provider & destination</button><button disabled={busy||!online} onClick={()=>act(async()=>setDiagnostic(JSON.stringify(await api('/settings/test',{}))))}>Discover saved models</button><button disabled={busy||!online} onClick={()=>act(async()=>setDiagnostic(JSON.stringify(await api('/settings/diagnostics'),null,2)))}>Inspect observed capabilities</button>{diagnostic&&<pre role="status">{diagnostic}</pre>}</section>
  <HostWorkerSettings online={online} provider={data?.provider} onChanged={refresh}/>
  <details><summary>Docker diagnostics</summary><SandboxSettings online={online}/></details>
  <WorkspaceSettings runs={data?.runs||[]} online={online} onChanged={refresh}/>
  <section><h2>Agent permissions</h2><label>Knowledge writes<select value={data?.writes||'ask'} onChange={e=>act(()=>api('/settings/permissions',{writes:e.target.value},'PUT'))}><option value="ask">Ask · exact single-action approval</option><option value="off">Off</option></select></label><p>Reading is scoped when you start a goal. Always-write is intentionally unavailable in this milestone.</p></section>
  <section><h2>Your devices</h2><p>{data?.phoneOrigin?'Phone address: '+data.phoneOrigin:'Phone HTTPS is not configured.'} A phone connects to this host, not its own localhost. The host must remain awake. Physical-device setup is unverified.</p><button disabled={busy||!online||!data?.phoneOrigin} onClick={()=>act(async()=>setPairCode((await api('/pair/start',{})).code))}>Create one-time pairing code</button>{pairCode&&<p className="pair-code">{pairCode} · expires in 5 minutes</p>}{devices.pending.map((p:any)=><div key={p.id}><span>{p.name} requests access</span><button onClick={()=>act(()=>api('/pair/'+p.id+'/confirm',{}))}>Confirm this device</button></div>)}{devices.devices.map((d:any)=><div className="device" key={d.id}><span>{d.name}<small>Expires {new Date(d.expires).toLocaleDateString()}</small></span><button onClick={()=>act(()=>api('/devices/'+d.id+'/revoke',{}))}>Revoke</button></div>)}</section>
  <section><h2>Your data, your exit</h2><a className="button" href="/api/export" download>Export notes & receipts</a><label>Delete all notes, runs, chats, collections & revisions<input placeholder="Type DELETE MY DATA" value={deleteText} onChange={e=>setDeleteText(e.target.value)}/></label><button disabled={deleteText!=='DELETE MY DATA'||!online||busy} onClick={()=>act(async()=>{await api('/data/delete',{confirmation:deleteText});setDeleteText('');setPage(null);})}>Delete my data</button><p>{data?.retainedResearchWorkspaces&&'Private research workspaces are retained. Remove them in Stored research workspaces above before deleting all task data. '}Storage is local and not application-encrypted. Deletion is not a secure disk erase. Sessions and provider settings remain.</p></section></>}<section><h2>Take the study with you</h2><p>On a supported browser, use “Install app” or “Add to Home Screen.” Trusted HTTPS is required for phone installation. Only the static shell is cached; private API data is not. Offline writes are never queued.</p></section></section>}

  </main></div>
  {logOpen&&<aside className="activity-log" id="activity-log" aria-label="Activity log"><div className="log-heading"><h2>Activity log</h2><button aria-label="Close activity log" onClick={()=>{setLogOpen(false);document.querySelector<HTMLButtonElement>('[aria-label="Activity log"]')?.focus();}}><X size={17}/></button></div><div className="companion"><Raven state={ravenState} onClick={()=>active&&showRun(active.id)}/><h2>Thaddeus</h2><p>{active?names[active.state]:online?'At your service.':'Disconnected'}</p></div><div className="log-caption"><span>RECORDED WORK</span><small>{data?.runs.length||0} runs</small></div><div className="log-entries">{data?.runs.length?ledger(data.runs):<p className="log-empty">Nothing in the ledger yet. I shall resist inventing an achievement.</p>}</div></aside>}
  </div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
if('serviceWorker' in navigator) navigator.serviceWorker.register('/sw.js').catch(()=>{});
