import {useCallback,useEffect,useRef,useState,type CSSProperties} from 'react';
import {ArrowRight,CalendarPlus,Check,CheckCircle2,ChevronDown,FileText,LayoutList,MessageCircle,PanelRightClose,PanelRightOpen,Plus,RefreshCw,Send,ShieldCheck,Users,X} from 'lucide-react';
import Markdown from 'react-markdown';
import {api} from '../api';
import {CompanyWorkspace} from './CompanyWorkspace';
import {MarketingDiscussion,readableTime,requestId,type MarketingState} from './MarketingPanels';
import {Raven} from './Raven';
import {PanelResize,initialPanelWidth,clampPanelWidth,panelWidthKey} from './PanelResize';
import {isPaused,needsDecision} from './WorkBoard';
import '../business.css';

type Member={id:string;name:string;role:string;departmentId:string|null;kind:string;runtimeKey:string|null};
type Directory={version:number;departments:{id:string;name:string;purpose:string}[];agents:Member[]};
type Action={title:string;outcome:string;taskId:string|null;state:string};
type Meeting={id:string;version:number;title:string;agenda:string;ethos:string;participants:string[];stage:string;messages:{id:string;speaker:string;content:string;createdAt:string}[];plan:{revision:number;summary:string;actions:Action[];requiresOwnerApproval:boolean;resources:string}|null;review:{revision:number;verdict:string;rationale:string;questions:string[]}|null;approvedRevision:number|null;approvedBy:string|null;error:string|null;createdAt:string;releaseAt:string|null};
const stageLabel:Record<string,string>={discussion:'Discussion',thinking:'Team is responding',plan:'Proposed plan',reviewed:'Review complete',approved:'Approved · veto window',releasing:'Assigning work',closed:'Meeting closed',vetoed:'Vetoed'};

function MeetingProgress({meeting}:{meeting:Meeting}){
  const step=['closed','releasing'].includes(meeting.stage)?3:meeting.review?2:meeting.plan?1:0;
  return <div className="meeting-progress" aria-label="Meeting progress">
    <ol>{['Discuss','Propose','Review','Assign'].map((label,index)=><li key={label} className={index<step?'complete':index===step?'current':''} aria-current={index===step?'step':undefined}><span>{index<step?<Check size={12}/>:index+1}</span>{label}</li>)}</ol>
    <span className="meeting-progress-status">{meeting.stage==='vetoed'?'Stopped by owner':meeting.stage==='thinking'?'Team responding':meeting.plan?`Plan v${meeting.plan.revision}`:'CEO chairs · Marketing plans'}</span>
  </div>;
}

function StartMeeting({ethos,onStart,onClose}:{ethos:string;onStart:(fields:object)=>Promise<void>;onClose:()=>void}){
  const ref=useRef<HTMLDialogElement>(null),attempt=useRef(requestId());
  const [title,setTitle]=useState(''),[agenda,setAgenda]=useState(''),[principles,setPrinciples]=useState(ethos),[busy,setBusy]=useState(false),[error,setError]=useState('');
  useEffect(()=>{ref.current?.showModal();},[]);
  return <dialog ref={ref} className="company-dialog" aria-label="Start a meeting" onCancel={e=>{e.preventDefault();if(!busy)onClose();}}><header><h2>Start a meeting</h2><button disabled={busy} aria-label="Close dialog" onClick={onClose}><X size={19}/></button></header><form className="company-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await onStart({requestId:attempt.current,title,agenda,ethos:principles,participants:['ceo','marketing'],action:'create',version:0});}catch(error){setError((error as Error).message);}finally{setBusy(false);}}}>
    <div className="meeting-setup-intro"><Users size={21}/><div><strong>Bring the team into the conversation</strong><p>A shared meeting with its own notes and action plan.</p></div></div><fieldset className="meeting-participants"><legend>Participants</legend><div><span className="meeting-avatar ceo">C</span><span><strong>CEO</strong><small>Chair · questions and final review</small></span><CheckCircle2 size={17}/></div><div><span className="meeting-avatar">M</span><span><strong>Marketing</strong><small>Planning · research and delivery</small></span><CheckCircle2 size={17}/></div><p>You can join, catch up later, or veto the plan.</p></fieldset><label>Meeting title<input autoFocus required maxLength={160} value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Find our first marketing customers"/></label>
    <label>Agenda<textarea required maxLength={4000} value={agenda} onChange={e=>setAgenda(e.target.value)} placeholder="What needs deciding? What should we leave with?"/></label>
    <details className="meeting-ethos-edit" open={!ethos.trim()?true:undefined}><summary>Review company ethos</summary><label>Company ethos<textarea required maxLength={4000} value={principles} onChange={e=>setPrinciples(e.target.value)} placeholder="The principles the CEO should use to judge the plan."/></label></details>
    <div className="meeting-attendees" hidden><span><ShieldCheck size={16}/> CEO · chair & review</span><span><Users size={16}/> Marketing · plan & delivery</span><span>You · direction & veto</span></div>
    <p className="company-form-note">The CEO opens with questions. Routine internal plans can proceed after CEO review and a two-minute veto window. Spending, substantial resources, or uncertainty require your approval. Every meeting keeps its notes.</p>
    {error&&<p role="alert" className="company-error">{error}</p>}<footer><button type="button" disabled={busy} onClick={onClose}>Cancel</button><button className="primary" disabled={busy}>{busy?'Opening…':'Start meeting'}</button></footer>
  </form></dialog>;
}

export function BusinessWorkspace({hostOnline}:{hostOnline:boolean}){
  const [mode,setMode]=useState<'chat'|'work'>('chat'),[state,setState]=useState<MarketingState|null>(null),[directory,setDirectory]=useState<Directory|null>(null);
  const [meetings,setMeetings]=useState<Meeting[]>([]),[meetingId,setMeetingId]=useState<string|null>(null),[memberId,setMemberId]=useState('marketing-main');
  const [readError,setReadError]=useState('');
  const [error,setError]=useState(''),[busy,setBusy]=useState(false),[starting,setStarting]=useState(false),[sideTab,setSideTab]=useState<'glance'|'members'|'conversations'>('glance');
  const [draft,setDraft]=useState(''),[workFocus,setWorkFocus]=useState<{view:'records'|'tasks'|'team'|'brief'|'approvals';scope?:{kind:'company'|'department'|'agent';id:string};taskId?:string;key:number}>({view:'tasks',key:0});
  const [panelOpen,setPanelOpen]=useState(()=>window.matchMedia('(min-width: 961px)').matches);
  const [panelWidth,setPanelWidth]=useState(initialPanelWidth),[resizing,setResizing]=useState(false);
  function resizePanel(width:number){setPanelWidth(width);try{localStorage.setItem(panelWidthKey,String(width));}catch{}}
  useEffect(()=>{const fit=()=>{if(window.innerWidth>960)setPanelWidth(width=>clampPanelWidth(width));};window.addEventListener('resize',fit);return()=>window.removeEventListener('resize',fit);},[]);
  const panelToggle=useRef<HTMLButtonElement>(null);
  const scrolling=useRef<HTMLDivElement>(null),attempt=useRef<{signature:string;id:string}|null>(null),refreshing=useRef(false);
  const refresh=useCallback(async()=>{
    if(refreshing.current)return;refreshing.current=true;
    try{const [s,o,m]=await Promise.all([api<MarketingState>('/marketing/state'),api<{directory:Directory}>('/organization'),api<Meeting[]>('/meetings')]);setState(s);setDirectory(o.directory);setMeetings(m);setReadError('');}catch(e){setReadError((e as Error).message);}finally{refreshing.current=false;}
  },[]);
  useEffect(()=>{void refresh();const timer=setInterval(()=>{if(document.visibilityState==='visible')void refresh();},8000);return()=>clearInterval(timer);},[refresh]);
  const meeting=meetings.find(m=>m.id===meetingId),member=directory?.agents.find(a=>a.id===memberId);
  const canWrite=hostOnline&&!readError&&state?.connection.status==='connected';
  const owner=state?.canConfigure===true;
  const pending=state?.tasks.filter(needsDecision)||[];
  const active=state?.tasks.filter(t=>t.status==='working')||[];
  const recent=state?.tasks.filter(t=>t.status!=='done'&&!isPaused(t)).sort((a,b)=>Number(needsDecision(b))-Number(needsDecision(a))).slice(0,3)||[];
  const meetingBusy=busy||meeting?.stage==='thinking';
  const ended=meeting&&['closed','vetoed','releasing'].includes(meeting.stage);
  useEffect(()=>{if(scrolling.current)scrolling.current.scrollTop=scrolling.current.scrollHeight;},[meeting?.messages.length,meetingId]);
  useEffect(()=>{try{setDraft(localStorage.getItem('meeting-draft:'+meetingId)||'');}catch{setDraft('');}},[meetingId]);
  function changeDraft(value:string){setDraft(value);try{localStorage.setItem('meeting-draft:'+meetingId,value);}catch{}}
  function work(view:typeof workFocus.view='tasks',scope?:typeof workFocus.scope,taskId?:string){setWorkFocus({view,scope,taskId,key:Date.now()});setMode('work');if(window.innerWidth<=960)setPanelOpen(false);}
  function closePanel(){setPanelOpen(false);panelToggle.current?.focus();}
  async function command(action:string,content?:string,current=meeting){
    if(!current)return;const fields={action,content,version:current.version},signature=current.id+JSON.stringify(fields);
    const id=attempt.current?.signature===signature?attempt.current.id:requestId();attempt.current={signature,id};
    const next=await api<Meeting>('/meetings/'+current.id,{...fields,requestId:id});
    attempt.current=null;setMeetings(items=>items.map(m=>m.id===next.id?next:m));return next;
  }
  async function act(action:string,content?:string){setBusy(true);setError('');try{await command(action,content);if(action==='message'||action==='revise')changeDraft('');await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function discuss(){if(!draft.trim())return;setBusy(true);setError('');try{const next=await command('message',draft.trim());changeDraft('');if(next)await command('ask-ceo',undefined,next);}catch(e){setError((e as Error).message);}finally{setBusy(false);void refresh();}}
  function openMeeting(m:Meeting){setMeetingId(m.id);setMode('chat');setSideTab('glance');if(window.innerWidth>960)setPanelOpen(true);else setPanelOpen(false);}
  const awaitingApproval=meetings.filter(m=>m.stage==='reviewed'&&m.plan?.requiresOwnerApproval&&m.review?.verdict==='accept');
  const approvalCount=awaitingApproval.length+(state?.drafts.filter(draft=>draft.status==='pending').length||0);
  const members=[{id:'ceo',name:'CEO',role:'Chair meetings · challenge & review',departmentId:null,kind:'manager',runtimeKey:'meeting-ceo'},...(directory?.agents||[]).filter(m=>m.id!=='ceo')];
  return <div className={'business-shell '+(resizing?'resizing-panel':'')} style={{'--company-panel-width':panelWidth+'px'} as CSSProperties}>
    <header className="business-header"><div className="business-wordmark"><span className="mark">T</span><div>THADDEUS<small>YOUR FIRST EMPLOYEE</small></div></div><nav aria-label="Main views"><button aria-current={mode==='chat'?'page':undefined} onClick={()=>setMode('chat')}><MessageCircle size={17}/>Chat</button><button aria-current={mode==='work'?'page':undefined} onClick={()=>setMode('work')}><LayoutList size={17}/>Work</button></nav><div className="business-header-end"><span className={'business-online '+(canWrite?'live':'')}>{canWrite?'Team online':state?.connection.status==='busy'?'Employee working':state?.connection.status==='auth_required'?'Sign-in needed':'Connecting'}</span><button aria-label="Refresh workspace" onClick={()=>void refresh()}><RefreshCw size={16}/></button><button ref={panelToggle} aria-label={panelOpen?'Hide company panel':'Show company panel'} title="Company panel" aria-expanded={panelOpen} aria-controls="company-panel" onClick={()=>setPanelOpen(!panelOpen)}>{panelOpen?<PanelRightClose size={19}/>:<PanelRightOpen size={19}/>}</button></div></header>
    {(error||readError||!hostOnline)&&<div className="business-alert" role="alert">{error||readError||'The host is offline. Reconnect before making changes.'}<button onClick={()=>{setError('');void refresh();}}>Reconnect</button></div>}
    <div className={'business-body '+(mode==='work'?'work-mode ':'')+(panelOpen?'':'panel-closed')}>
      <main className="business-main" aria-label={mode==='chat'?'Chat workspace':'Work workspace'}>
      {mode==='work'?<><CompanyWorkspace hostOnline={hostOnline} focus={workFocus} meetingApprovalCount={awaitingApproval.length} meetingApprovals={awaitingApproval.length>0&&<section className="work-meeting-approvals" aria-label="Meeting approvals"><h2>Plans awaiting your approval</h2>{awaitingApproval.map(m=><button key={m.id} onClick={()=>openMeeting(m)}><ShieldCheck size={20}/><span><strong>{m.title}</strong><small>{m.plan!.resources}</small></span><span>Review plan <ArrowRight size={15}/></span></button>)}</section>}/><section className="work-meeting-archive"><h2>Meeting notes</h2><p>Agendas, decisions, and the plan behind each assignment.</p>{meetings.length?meetings.map(m=><button key={m.id} onClick={()=>openMeeting(m)}><FileText size={18}/><span><strong>{m.title}</strong><small>{readableTime(m.createdAt)} · {stageLabel[m.stage]}</small></span><ArrowRight size={16}/></button>):<p>No meetings recorded yet.</p>}</section></>:<>
        <div className="business-conversation-title"><div><p className="eyebrow">{meeting?'MEETING ROOM':member?.departmentId?directory?.departments.find(d=>d.id===member.departmentId)?.name?.toUpperCase():'MARKETING'}</p><h1>{meeting?meeting.title:member?.name||state?.employee.name||'Marketing agent'}</h1><p>{meeting?<><span className="meeting-stage">{stageLabel[meeting.stage]}</span> CEO · Marketing · You</>:member?.runtimeKey===null?'This member needs a connection before joining conversations.':'Your employee’s direct conversation. Turn decisions into work.'}</p></div><div className="conversation-actions">{!meeting&&<button className="add-to-chat" disabled={!owner||!hostOnline} onClick={()=>setStarting(true)}><Users size={16}/>Add to chat</button>}<button className="business-meeting-button" disabled={!owner||!hostOnline} onClick={()=>setStarting(true)}><CalendarPlus size={17}/>Start meeting</button></div></div>
        {!state?<div className="company-empty">Opening your conversations…</div>:meeting?<section className="meeting-conversation" aria-label="Meeting conversation"><MeetingProgress meeting={meeting}/>
          <div className="meeting-transcript" ref={scrolling}><article className="meeting-agenda-message"><span className="meeting-avatar">M</span><div><strong>Meeting opened <time>{readableTime(meeting.createdAt)}</time></strong><h2>{meeting.title}</h2><p>{meeting.agenda}</p><small>CEO asks and reviews. Marketing proposes and delivers. You retain veto power.</small></div></article>
          {meeting.messages.map(message=><article className={'meeting-message '+(message.speaker==='You'?'from-owner':'')} key={message.id}><span className={'meeting-avatar '+(message.speaker==='CEO'?'ceo':'')}>{message.speaker==='CEO'?'C':message.speaker==='Marketing'?'M':message.speaker==='You'?'Y':'T'}</span><div><div className="meeting-message-byline"><strong>{message.speaker}</strong><time>{readableTime(message.createdAt)}</time></div><Markdown>{message.content}</Markdown></div></article>)}
          {meetingBusy&&<p className="meeting-thinking" role="status">The team is considering the meeting…</p>}{meeting.error&&<p className="company-error" role="alert">{meeting.error}</p>}</div>
          {ended?<div className="meeting-ended"><CheckCircle2 size={18}/><span>{meeting.stage==='vetoed'?'Plan vetoed. Pending work is stopped.':'Notes are saved. Follow the assignments in Work.'}</span><button onClick={()=>work('tasks')}>Open board <ArrowRight size={15}/></button></div>:<div className="meeting-composer"><div className="meeting-next-step"><span>{meeting.review?.verdict==='revise'?'The CEO requested changes. Add direction or develop a revised plan.':meeting.stage==='approved'?'The plan will start after the veto window. You can stop it from the sidebar.':meeting.review?.verdict==='accept'?'The plan is accepted. Review its resource request in the sidebar.':'Discuss the need, then ask Marketing to develop a plan.'}</span><button disabled={meetingBusy||!canWrite||!owner} onClick={()=>void act('propose')}>{meeting.plan?'Revise plan & review':'Develop plan & review'} <ArrowRight size={14}/></button></div><form onSubmit={e=>{e.preventDefault();void discuss();}}><textarea aria-label="Message to meeting" value={draft} onChange={e=>changeDraft(e.target.value)} disabled={meetingBusy||!canWrite||!owner} placeholder="Give direction, answer the CEO, or challenge the plan…"/><div><small>CEO responds to your message · Enter a clear outcome</small><button className="primary" disabled={meetingBusy||!canWrite||!owner||!draft.trim()}><Send size={16}/>Send</button></div></form></div>}
        </section>:member?.runtimeKey===null?<div className="company-empty"><Users size={28}/><h2>Ready for a future colleague</h2><p>Connect this member’s runtime to start a conversation.</p><button onClick={()=>work('team')}>Manage team</button></div>:<MarketingDiscussion state={state} canWrite={!!canWrite} onRefresh={refresh}/>}
      </>}
      </main>
      {panelOpen&&<><PanelResize width={panelWidth} onChange={resizePanel} onDragging={setResizing}/><button className="company-panel-backdrop" aria-label="Dismiss company panel" onClick={closePanel}/><aside id="company-panel" className="business-sidebar" aria-label="Company sidebar" onKeyDown={event=>{if(event.key==='Escape')closePanel();}}><div className="business-panel-heading"><span>Company panel</span><button aria-label="Close company panel" onClick={closePanel}><X size={17}/></button></div><div className="business-panel-identity"><Raven state={meetingBusy?'listening':'idle'}/><strong>{meeting?'Meeting room':'Your first employee'}</strong><span><i className={canWrite?'live':''}/>{meeting?'CEO · Marketing · You':canWrite?'Team connected':'Connection pending'}</span></div><nav className="business-side-tabs" aria-label="Sidebar views"><button aria-pressed={sideTab==='glance'} onClick={()=>setSideTab('glance')}>At a glance</button><button aria-label="All members" aria-pressed={sideTab==='members'} onClick={()=>setSideTab('members')}><Users size={15}/><span>Members</span></button><button aria-label="Department conversations" aria-pressed={sideTab==='conversations'} onClick={()=>setSideTab('conversations')}><MessageCircle size={15}/><span>Chats</span></button></nav>
      {sideTab==='glance'?<>
        <section className="business-glance"><p className="eyebrow">TODAY’S BUSINESS</p><div className="business-metrics"><button onClick={()=>work(approvalCount?'approvals':'tasks')}><strong>{pending.length+approvalCount}</strong><span>Decisions</span></button><button onClick={()=>work('tasks')}><strong>{active.length}</strong><span>In progress</span></button><button onClick={()=>setSideTab('members')}><strong>{members.length}</strong><span>Members</span></button></div></section>
        {meeting?<><section className="business-side-section"><div className="side-section-title"><h2>Meeting agenda</h2><span>{stageLabel[meeting.stage]}</span></div><p className="meeting-sidebar-agenda">{meeting.agenda}</p><details><summary>Company ethos <ChevronDown size={14}/></summary><p>{meeting.ethos}</p></details></section><section className="business-side-section action-plan"><div className="side-section-title"><h2>Action plan</h2>{meeting.plan&&<span>v{meeting.plan.revision}</span>}</div>{meeting.plan?<><p>{meeting.plan.summary}</p><ol>{meeting.plan.actions.map((item,i)=><li key={i}><strong>{item.title}</strong><small>{item.outcome}</small><span>Marketing · {item.state.replaceAll('_',' ')}</span>{item.taskId&&<button onClick={()=>work('tasks',undefined,item.taskId!)}>View on board <ArrowRight size={13}/></button>}</li>)}</ol><div className={'meeting-resource-gate '+(meeting.plan.requiresOwnerApproval?'gated':'')}><ShieldCheck size={16}/><div><strong>{meeting.plan.requiresOwnerApproval?'Your approval required':'Routine internal work'}</strong><p>{meeting.plan.resources}</p></div></div>{meeting.review&&<div className="meeting-review-note"><strong>CEO · {meeting.review.verdict==='accept'?'Accept':'Revise'}</strong><p>{meeting.review.rationale}</p>{meeting.review.questions.length>0&&<div className="meeting-open-questions"><strong>Open questions</strong><ul>{meeting.review.questions.map((q,i)=><li key={i}>{q}</li>)}</ul></div>}</div>}{meeting.releaseAt&&meeting.stage==='approved'&&<p className="meeting-release-note">Starts after {new Date(meeting.releaseAt).toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit'})}. You can veto below.</p>}
        {owner&&meeting.review?.verdict==='accept'&&!ended&&meeting.stage!=='approved'&&<button className="primary" disabled={meetingBusy||!hostOnline} onClick={()=>void act('approve')}>Approve plan & close meeting</button>}
        {owner&&meeting.stage==='approved'&&<button className="primary" disabled={meetingBusy||!hostOnline} onClick={()=>void act('close')}>Close & start now</button>}
        </>:<div className="meeting-plan-empty"><LayoutList size={25}/><p>The plan takes shape here as the meeting progresses.</p><small>Each action will have an owner and a clear outcome.</small></div>}
        {owner&&meeting.stage!=='vetoed'&&<button className="meeting-veto" disabled={!hostOnline} onClick={()=>void act('veto')}>Veto plan & stop pending work</button>}{meeting.plan?.actions.some(a=>a.state==='working')&&<small className="meeting-running-note">An active turn may still finish after a veto. Its result remains in the task record.</small>}</section></>:<><section className="business-side-section"><div className="side-section-title"><h2>Next actions</h2><button onClick={()=>work('tasks')}>Board <ArrowRight size={14}/></button></div>{recent.length?recent.map(task=><button className="business-next-action" key={task.id} onClick={()=>work('tasks',undefined,task.id)}><span className={'company-priority-dot '+task.priority}/><span><strong>{task.title}</strong><small>{task.status==='needs_you'?'Needs your decision':task.status==='working'?'Marketing is working':'Ready for Marketing'}</small></span></button>):<p className="sidebar-muted">Agreed assignments will appear here.</p>}</section><section className="business-side-section"><div className="side-section-title"><h2>Meeting room</h2><CalendarPlus size={17}/></div><p className="sidebar-muted">Bring the team together. Clarify the need, agree a plan, and give everyone their next action.</p><button className="business-wide-button" disabled={!owner} onClick={()=>setStarting(true)}>Start a meeting <Plus size={15}/></button>{meetings.slice(0,4).map(m=><button key={m.id} className="sidebar-meeting-link" onClick={()=>openMeeting(m)}><strong>{m.title}</strong><small>{stageLabel[m.stage]} · {readableTime(m.createdAt)}</small></button>)}</section><section className="business-side-section"><div className="side-section-title"><h2>Saved work</h2><FileText size={17}/></div><p className="sidebar-muted">Research, replies, drafts, and decision records.</p><button className="business-wide-button" onClick={()=>work('records')}>Open records <ArrowRight size={15}/></button></section></>}
      </>:sideTab==='members'?<section className="business-side-section"><div className="side-section-title"><h2>All members</h2><button onClick={()=>work('team')}>Manage <ArrowRight size={14}/></button></div>{members.map(item=><button key={item.id} className="business-member" onClick={()=>{if(item.id==='ceo'){setStarting(true);return;}setMemberId(item.id);setMeetingId(null);setMode('chat');}}><span className={'meeting-avatar '+(item.kind==='manager'?'ceo':'')}>{item.name.slice(0,1)}</span><span><strong>{item.name}</strong><small>{item.role}</small><em>{item.runtimeKey==='meeting-ceo'?'Meeting chair':item.runtimeKey?'Connected':'Setup needed'}</em></span></button>)}</section>:<section className="business-side-section"><div className="side-section-title"><h2>Conversations</h2></div>{directory?.departments.map(department=><div className="department-conversations" key={department.id}><h3>{department.name}</h3>{directory.agents.filter(a=>a.departmentId===department.id).map(item=><button key={item.id} aria-pressed={!meetingId&&memberId===item.id} onClick={()=>{setMemberId(item.id);setMeetingId(null);setMode('chat');}}><MessageCircle size={15}/>{item.name}</button>)}</div>)}<h3 className="sidebar-subheading">Cross-department meetings</h3>{meetings.map(m=><button key={m.id} className="sidebar-meeting-link" aria-pressed={meetingId===m.id} onClick={()=>openMeeting(m)}><strong>{m.title}</strong><small>{stageLabel[m.stage]}</small></button>)}{!meetings.length&&<p className="sidebar-muted">Start a meeting to create a shared conversation.</p>}<button className="business-wide-button" onClick={()=>setStarting(true)} disabled={!owner}>New meeting <Plus size={15}/></button></section>}
      <div className="business-sidebar-foot"><ShieldCheck size={14}/><span>CEO approves routine work.<br/>You control spending, resources, and vetoes.</span></div></aside></>}
    </div>
    {starting&&<StartMeeting ethos={state?.profile.guardrails||''} onClose={()=>setStarting(false)} onStart={async fields=>{const created=await api<Meeting>('/meetings',fields);setMeetings(items=>[created,...items.filter(m=>m.id!==created.id)]);setMeetingId(created.id);setMode('chat');setSideTab('glance');setStarting(false);setBusy(true);try{await command('ask-ceo',undefined,created);}catch(e){setError((e as Error).message);}finally{setBusy(false);void refresh();}}}/>}
  </div>;
}
