import {useCallback,useEffect,useRef,useState,type CSSProperties} from 'react';
import {ArrowLeft,ArrowRight,CalendarPlus,Check,CheckCircle2,ChevronDown,Download,FileText,LayoutList,MessageCircle,PanelRightClose,PanelRightOpen,Plus,RefreshCw,Search,Send,ShieldCheck,Users,X} from 'lucide-react';
import Markdown from 'react-markdown';
import {api} from '../api';
import {CompanyWorkspace} from './CompanyWorkspace';
import {MarketingDiscussion,readableTime,requestId,type MarketingState} from './MarketingPanels';
import {Raven} from './Raven';
import {PanelResize,initialPanelWidth,clampPanelWidth,panelWidthKey} from './PanelResize';
import {isPaused,needsDecision} from './WorkBoard';
import '../business.css';

type Member={id:string;name:string;role:string;departmentId:string|null;kind:string;runtimeKey:string|null};
type Directory={version:number;departments:{id:string;name:string;purpose:string}[];agents:Member[]};
type Action={title:string;outcome:string;taskId:string|null;state:string;kind:string};
type Grant={id:string;approver:string;authoritySource:string;approvedAt:string;expiresAt:string;planRevision:number;planDigest:string;sourceUrls:string[];allowedActionTypes:string[];capabilities:string[];artifactDestination:string;maxAssignedTasks:number;maxDispatchAttempts:number;dispatchAttempts:number;executionDeadline:string;modelRoute:string;allowFallback:boolean;revoked:boolean;taskIds:string[]|null;dispatchIds:string[]|null};
type Artifact={id:string;taskId:string;kind:string;content:string;digest:string;producedAt:string;ownerAccepted:boolean;sourceUrls:string[]|null;evidenceIds:string[]|null;acceptedBy:string|null;acceptedAt:string|null};
type Meeting={id:string;version:number;title:string;agenda:string;ethos:string;participants:string[];stage:string;messages:{id:string;speaker:string;content:string;createdAt:string}[];plan:{revision:number;summary:string;actions:Action[];requiresOwnerApproval:boolean;resources:string;profile:string}|null;review:{revision:number;verdict:string;rationale:string;questions:string[]}|null;approvedRevision:number|null;approvedBy:string|null;error:string|null;createdAt:string;releaseAt:string|null;grant:Grant|null;artifacts:Artifact[]|null;proposalDigest:string|null;contextSnapshots?:{memberId:string;role:string;capturedAt:string;pages:{id:string;version:number;digest:string;title:string;kind:string;scope:string;scopeId:string}[]}[]|null};
const meetingsPaused=true;
const stageLabel:Record<string,string>={discussion:'Discussion',thinking:'Team is responding',plan:'Proposed plan',reviewed:'Review complete',approved:'Legacy approval · paused',releasing:'Assigning work',closed:'Meeting closed',paused:'Work paused',vetoed:'Vetoed'};

function meetingDecision(meeting:Meeting){
  if(meeting.grant?.revoked||meeting.stage==='vetoed')return 'Vetoed by owner';
  if(meeting.grant)return `Owner granted plan v${meeting.grant.planRevision}`;
  if(meeting.review?.verdict==='accept')return `CEO recommended plan v${meeting.review.revision} · owner grant pending`;
  if(meeting.review?.verdict==='revise')return 'CEO requested revision';
  return 'No final decision recorded';
}

function MeetingArchive({meetings,onOpen,onStart,canStart}:{meetings:Meeting[];onOpen:(meeting:Meeting)=>void;onStart:()=>void;canStart:boolean}){
  const [query,setQuery]=useState(''),[filter,setFilter]=useState<'all'|'needs_you'|'completed'>('all');
  const listed=meetings.filter(meeting=>{
    const matches=(meeting.title+' '+meeting.agenda+' '+meeting.participants.join(' ')).toLowerCase().includes(query.toLowerCase().trim());
    const needsYou=meeting.stage==='reviewed'&&meeting.review?.verdict==='accept'&&!meeting.grant||
      (meeting.artifacts||[]).some(item=>item.kind==='local_draft'&&!item.ownerAccepted);
    return matches&&(filter==='all'||filter==='needs_you'&&needsYou||filter==='completed'&&['closed','vetoed'].includes(meeting.stage));
  });
  return <section className="meeting-archive" aria-label="Meeting history"><header><div><p className="eyebrow">COMPANY RECORDS</p><h1>Past meetings</h1><p>Saved pilot conversations, decisions, and results. New meetings are paused while Marketing is your only employee.</p></div>{!meetingsPaused&&<button className="primary" disabled={!canStart} onClick={onStart}><CalendarPlus size={16}/>Start meeting</button>}</header>
    <div className="meeting-archive-controls"><label><Search size={16}/><input aria-label="Search meetings" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search titles and agendas"/></label><select aria-label="Filter meetings" value={filter} onChange={event=>setFilter(event.target.value as typeof filter)}><option value="all">All meetings</option><option value="needs_you">Needs you</option><option value="completed">Closed or vetoed</option></select></div>
    <div className="meeting-archive-list">{listed.map(meeting=><button key={meeting.id} onClick={()=>onOpen(meeting)}><span className="meeting-archive-icon"><Users size={18}/></span><span className="meeting-archive-copy"><strong>{meeting.title}</strong><small>{readableTime(meeting.createdAt)} · {stageLabel[meeting.stage]} · CEO + Marketing</small><span>{meetingDecision(meeting)} · {(meeting.artifacts||[]).length} saved result{(meeting.artifacts||[]).length===1?'':'s'}</span></span><ArrowRight size={16}/></button>)}{!listed.length&&<p className="meeting-archive-empty">{meetings.length?'No meetings match this search.':'No past meetings yet.'}</p>}</div>
  </section>;
}

function MeetingAudit({meeting,onArtifact,onTask}:{meeting:Meeting;onArtifact:(id:string)=>void;onTask:(id:string)=>void}){
  const artifacts=meeting.artifacts||[];
  return <section className="meeting-audit" aria-label="Meeting decision and results"><div className="meeting-audit-heading"><h2>Decision & results</h2><span>{stageLabel[meeting.stage]}</span></div><div className="meeting-audit-grid"><div><strong>Decision</strong><p>{meetingDecision(meeting)}</p>{meeting.review&&<small>CEO: {meeting.review.rationale}</small>}{meeting.grant&&<small>Grant {meeting.grant.id.slice(0,8)} · plan digest {meeting.grant.planDigest.slice(0,12)} · {meeting.grant.dispatchAttempts}/{meeting.grant.maxDispatchAttempts} dispatches</small>}</div><div><strong>Plan</strong><p>{meeting.plan?.summary||'No plan recorded.'}</p>{meeting.plan&&<small>Revision {meeting.plan.revision} · {meeting.plan.actions.length} proposed action{meeting.plan.actions.length===1?'':'s'}</small>}</div><div><strong>Results</strong>{artifacts.length?<ul>{artifacts.map(item=><li key={item.id}><button onClick={()=>onArtifact(item.id)}>{item.kind==='local_draft'?'Local draft':'Evidence brief'} · {item.ownerAccepted?'owner accepted':'for review'} <ArrowRight size={13}/></button></li>)}</ul>:<p>No artifacts recorded.</p>}{meeting.plan?.actions.filter(item=>item.taskId).map(item=><button className="meeting-audit-task" key={item.taskId} onClick={()=>onTask(item.taskId!)}>{item.title} · {item.state} <ArrowRight size={13}/></button>)}</div></div><details><summary>Audit details</summary><dl><div><dt>Meeting ID</dt><dd>{meeting.id}</dd></div><div><dt>Participants</dt><dd>{meeting.participants.join(', ')}</dd></div><div><dt>Owner grant</dt><dd>{meeting.grant?`${meeting.grant.approver} · ${meeting.grant.approvedAt}`:'None'}</dd></div><div><dt>Source scope</dt><dd>{meeting.grant?.sourceUrls.join(' · ')||'No execution source grant'}</dd></div><div><dt>Role and wiki snapshot</dt><dd>{meeting.contextSnapshots?.length?meeting.contextSnapshots.map(snapshot=><p key={snapshot.memberId}><strong>{snapshot.role} · {snapshot.memberId}</strong> · captured {readableTime(snapshot.capturedAt)} · {snapshot.pages.length} published page{snapshot.pages.length===1?'':'s'}{snapshot.pages.length>0&&<ul>{snapshot.pages.map(page=><li key={page.id}>{page.title} v{page.version} · {page.kind} · {page.scope} · {page.digest.slice(0,12)}</li>)}</ul>}</p>):'Not recorded for this older meeting. Member wiki access was not yet implemented.'}</dd></div></dl></details></section>;
}

function MeetingProgress({meeting}:{meeting:Meeting}){
  const step=meeting.stage==='closed'?4:meeting.stage==='releasing'?3:meeting.review?2:meeting.plan?1:0;
  return <div className="meeting-progress" aria-label="Meeting progress">
    <ol>{['Discuss','Propose','Review','Assign'].map((label,index)=><li key={label} className={index<step?'complete':index===step?'current':''} aria-current={index===step?'step':undefined}><span>{index<step?<Check size={12}/>:index+1}</span>{label}</li>)}</ol>
    <span className="meeting-progress-status">{meeting.stage==='vetoed'?'Stopped by owner':meeting.stage==='thinking'?'Team responding':meeting.plan?`Plan v${meeting.plan.revision}`:'CEO chairs · Marketing plans'}</span>
  </div>;
}

function StartMeeting({ethos,model,onStart,onClose}:{ethos:string;model:string;onStart:(fields:object)=>Promise<void>;onClose:()=>void}){
  const ref=useRef<HTMLDialogElement>(null),attempt=useRef(requestId());
  const [title,setTitle]=useState(''),[agenda,setAgenda]=useState(''),[principles,setPrinciples]=useState(ethos),[busy,setBusy]=useState(false),[error,setError]=useState('');
  useEffect(()=>{ref.current?.showModal();},[]);
  return <dialog ref={ref} className="company-dialog" aria-label="Start a meeting" onCancel={e=>{e.preventDefault();if(!busy)onClose();}}><header><h2>Start a meeting</h2><button disabled={busy} aria-label="Close dialog" onClick={onClose}><X size={19}/></button></header><form className="company-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await onStart({requestId:attempt.current,title,agenda,ethos:principles,participants:['ceo','marketing'],action:'create',version:0});}catch(error){setError((error as Error).message);}finally{setBusy(false);}}}>
    <div className="meeting-setup-intro"><Users size={21}/><div><strong>Bring the team into the conversation</strong><p>A shared meeting with its own notes and action plan.</p></div></div><fieldset className="meeting-participants"><legend>Participants</legend><div><span className="meeting-avatar ceo">C</span><span><strong>CEO</strong><small>Chair · questions and recommendation</small></span><CheckCircle2 size={17}/></div><div><span className="meeting-avatar">M</span><span><strong>Marketing</strong><small>Planning · research and delivery</small></span><CheckCircle2 size={17}/></div><p>You can join, catch up later, or veto the plan.</p></fieldset><label>Meeting title<input autoFocus required maxLength={160} value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Find our first marketing customers"/></label>
    <label>Agenda<textarea required maxLength={4000} value={agenda} onChange={e=>setAgenda(e.target.value)} placeholder="What needs deciding? What should we leave with?"/></label>
    <details className="meeting-ethos-edit" open={!ethos.trim()?true:undefined}><summary>Review company ethos</summary><label>Company ethos<textarea required maxLength={4000} value={principles} onChange={e=>setPrinciples(e.target.value)} placeholder="The principles the CEO should use to judge the plan."/></label></details>
    <div className="meeting-attendees" hidden><span><ShieldCheck size={16}/> CEO · chair & review</span><span><Users size={16}/> Marketing · plan & delivery</span><span>You · direction & veto</span></div>
    <p className="company-form-note">This opens a separate CEO–Marketing meeting with its own notes and pins each member's published wiki pages. Direct chat history is not copied. Starting invokes the CEO on {model} through the existing subscription; the meeting allows at most eight top-level model turns and one plan revision. Provider request count and charges may differ. The CEO recommends a plan; only your later approval of its exact scope can release the two-task local pilot. No fallback or external action is authorized.</p>
    {error&&<p role="alert" className="company-error">{error}</p>}<footer><button type="button" disabled={busy} onClick={onClose}>Cancel</button><button className="primary" disabled={busy}>{busy?'Opening…':'Start meeting'}</button></footer>
  </form></dialog>;
}

function MeetingRecap({meeting,state,onTask,onArtifact,onApproval}:{meeting:Meeting;state:MarketingState;onTask:(id:string)=>void;onArtifact:(id:string)=>void;onApproval:()=>void}){
  const linked=(meeting.plan?.actions||[]).map(action=>({action,task:state.tasks.find(task=>task.id===action.taskId)}));
  const artifacts=meeting.artifacts||[];
  const reviewNeeded=artifacts.find(item=>item.kind==='local_draft'&&!item.ownerAccepted);
  const pendingGrant=!meetingsPaused&&meeting.stage==='reviewed'&&meeting.review?.verdict==='accept'&&!meeting.grant;
  return <section className="meeting-recap" aria-label="Meeting return recap">
    <h2>Meeting recap</h2>
    <div><strong>Decided</strong><p>{meeting.grant?`Plan v${meeting.grant.planRevision||meeting.plan?.revision} approved by ${meeting.grant.approver}. ${meeting.grant.revoked?'Grant revoked.':'Restricted local work only.'}`:meeting.review?.verdict==='accept'?`CEO recommended plan v${meeting.plan?.revision}; owner approval is still needed.`:meeting.review?.verdict==='revise'?'CEO requested changes.':'No plan decision yet.'}</p></div>
    <div><strong>Delivered</strong>{artifacts.length?<ul>{artifacts.map(item=><li key={item.id}><button onClick={()=>onArtifact(item.id)}>{item.kind==='local_draft'?'Local draft':'Evidence brief'} · {item.ownerAccepted?'owner accepted':'produced for review'} <ArrowRight size={13}/></button></li>)}</ul>:<p>No output recorded yet.</p>}</div>
    <div><strong>In progress / blocked</strong>{linked.some(({action,task})=>task||action.taskId)?<ul>{linked.map(({action,task},i)=><li key={i}><button onClick={()=>action.taskId&&onTask(action.taskId)} disabled={!action.taskId}>{action.title} · {task?.status||action.state}{task?.blocker?` · ${task.blocker}`:''} <ArrowRight size={13}/></button></li>)}</ul>:<p>No tasks assigned.</p>}{meeting.error&&<p className="company-error">{meeting.error}</p>}</div>
    <div><strong>Needs you</strong>{pendingGrant?<button onClick={onApproval}>Review and approve exact scope <ArrowRight size={13}/></button>:reviewNeeded?<button onClick={()=>onArtifact(reviewNeeded.id)}>Review local draft <ArrowRight size={13}/></button>:meeting.error?<p>Inspect the saved error and board before continuing.</p>:<p>No decision requested now.</p>}</div>
  </section>;
}

export function BusinessWorkspace({hostOnline}:{hostOnline:boolean}){
  const [mode,setMode]=useState<'chat'|'work'>('chat'),[state,setState]=useState<MarketingState|null>(null),[directory,setDirectory]=useState<Directory|null>(null);
  const [meetings,setMeetings]=useState<Meeting[]>([]),[meetingId,setMeetingId]=useState<string|null>(()=>new URLSearchParams(window.location.search).get('meeting')),[memberId,setMemberId]=useState('marketing-main');
  const [chatView,setChatView]=useState<'conversation'|'meetings'>(()=>new URLSearchParams(window.location.search).get('view')==='meetings'?'meetings':'conversation');
  const [readError,setReadError]=useState('');
  const [error,setError]=useState(''),[busy,setBusy]=useState(false),[starting,setStarting]=useState(false),[sideTab,setSideTab]=useState<'glance'|'members'|'conversations'>('glance');
  const [draft,setDraft]=useState(''),[workFocus,setWorkFocus]=useState<{view:'records'|'tasks'|'team'|'brief'|'approvals'|'wiki';scope?:{kind:'company'|'department'|'agent';id:string};taskId?:string;reviewId?:string;key:number}>({view:'tasks',key:0});
  const [selectedSourceUrls,setSelectedSourceUrls]=useState<string[]>([]);
  const [panelOpen,setPanelOpen]=useState(()=>window.matchMedia('(min-width: 961px)').matches);
  const [panelWidth,setPanelWidth]=useState(initialPanelWidth),[resizing,setResizing]=useState(false);
  function resizePanel(width:number){setPanelWidth(width);try{localStorage.setItem(panelWidthKey,String(width));}catch{}}
  useEffect(()=>{const fit=()=>{if(window.innerWidth>960)setPanelWidth(width=>clampPanelWidth(width));};window.addEventListener('resize',fit);return()=>window.removeEventListener('resize',fit);},[]);
  const panelToggle=useRef<HTMLButtonElement>(null);
  const scrolling=useRef<HTMLDivElement>(null),attempt=useRef<{signature:string;id:string}|null>(null),refreshing=useRef(false);
  const refresh=useCallback(async()=>{
    if(refreshing.current)return;refreshing.current=true;
    try{const [s,o,m]=await Promise.all([api<MarketingState>('/marketing/state'),api<{directory:Directory}>('/organization'),api<Meeting[]>('/meetings')]);setState(s);setDirectory(o.directory);setMeetings(m);setReadError('');}catch(e){setReadError((e as Error).message);}finally{refreshing.current=false;}
  },[]);
  useEffect(()=>{void refresh();const timer=setInterval(()=>{if(document.visibilityState==='visible')void refresh();},8000);return()=>clearInterval(timer);},[refresh]);
  const meeting=meetings.find(m=>m.id===meetingId),member=directory?.agents.find(a=>a.id===memberId);
  const canWrite=hostOnline&&!readError&&state?.connection.status==='connected';
  const owner=state?.canConfigure===true;
  const pastMeetingTaskIds=new Set(meetings.filter(item=>meetingsPaused||['closed','vetoed'].includes(item.stage))
    .flatMap(item=>item.plan?.actions.flatMap(action=>action.taskId?[action.taskId]:[])||[]));
  const currentTasks=state?.tasks.filter(task=>!pastMeetingTaskIds.has(task.id))||[];
  const pending=currentTasks.filter(needsDecision);
  const active=currentTasks.filter(task=>task.status==='working');
  const draftReviewArtifact=state?.runway?.project.status==='needs_review'?state.runway.artifacts.find(artifact=>
    ['post_angles','revision_angles'].includes(artifact.kind)&&!state.runway?.reviews.some(review=>review.artifact_id===artifact.id)):undefined;
  const draftReviewPending=Boolean(draftReviewArtifact);
  const recent=currentTasks.filter(task=>task.status!=='done'&&!isPaused(task)).sort((a,b)=>Number(needsDecision(b))-Number(needsDecision(a))).slice(0,draftReviewPending?2:3);
  const meetingBusy=busy||meeting?.stage==='thinking';
  const ended=meeting&&['closed','vetoed','releasing'].includes(meeting.stage);
  useEffect(()=>{if(scrolling.current&&meeting)scrolling.current.scrollTop=['closed','vetoed'].includes(meeting.stage)?0:scrolling.current.scrollHeight;},[meeting?.messages.length,meetingId,meeting?.stage]);
  useEffect(()=>{try{setDraft(localStorage.getItem('meeting-draft:'+meetingId)||'');}catch{setDraft('');}},[meetingId]);
  useEffect(()=>{setSelectedSourceUrls([]);},[meetingId]);
  function changeDraft(value:string){setDraft(value);try{localStorage.setItem('meeting-draft:'+meetingId,value);}catch{}}
  function work(view:typeof workFocus.view='tasks',scope?:typeof workFocus.scope,taskId?:string,reviewId?:string){setWorkFocus({view,scope,taskId,reviewId,key:Date.now()});setMode('work');if(window.innerWidth<=960)setPanelOpen(false);}
  function closePanel(){setPanelOpen(false);panelToggle.current?.focus();}
  async function command(action:string,content?:string,current=meeting,extra:Record<string,unknown>={}){
    if(!current)return;const fields={action,content,version:current.version,...extra},signature=current.id+JSON.stringify(fields);
    const id=attempt.current?.signature===signature?attempt.current.id:requestId();attempt.current={signature,id};
    const next=await api<Meeting>('/meetings/'+current.id,{...fields,requestId:id});
    attempt.current=null;setMeetings(items=>items.map(m=>m.id===next.id?next:m));return next;
  }
  async function act(action:string,content?:string,extra:Record<string,unknown>={}){setBusy(true);setError('');try{await command(action,content,meeting,extra);if(action==='message'||action==='revise')changeDraft('');await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function discuss(){if(!draft.trim())return;setBusy(true);setError('');try{const next=await command('message',draft.trim());changeDraft('');if(next)await command('ask-ceo',undefined,next);}catch(e){setError((e as Error).message);}finally{setBusy(false);void refresh();}}
  function setMeetingRoute(id:string|null,archive=false){const url=new URL(window.location.href);url.searchParams.delete('meeting');url.searchParams.delete('view');if(id)url.searchParams.set('meeting',id);else if(archive)url.searchParams.set('view','meetings');window.history.replaceState(window.history.state,'',url);}
  function showMeetings(){setMeetingId(null);setChatView('meetings');setMode('chat');setMeetingRoute(null,true);}
  function showChat(){setMeetingId(null);setChatView('conversation');setMode('chat');setMeetingRoute(null);}
  function openMeeting(m:Meeting){setMeetingId(m.id);setChatView('conversation');setMode('chat');setSideTab('glance');setMeetingRoute(m.id);if(window.innerWidth>960)setPanelOpen(true);else setPanelOpen(false);}
  function openArtifact(id:string){requestAnimationFrame(()=>document.getElementById('meeting-artifact-'+id)?.scrollIntoView({behavior:'smooth',block:'center'}));}
  function downloadMeeting(m:Meeting){const url=URL.createObjectURL(new Blob([JSON.stringify(m,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download=`meeting-${m.id}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  const awaitingApproval=meetings.filter(m=>m.stage==='reviewed'&&m.review?.verdict==='accept'&&!m.grant);
  const meetingSources=[...new Map((state?.evidence||[]).filter(item=>/^https:\/\/news\.ycombinator\.com\/item\?id=\d+$/.test(item.url)).map(item=>[item.url,item])).values()];
  const readyToApprove=meeting?.plan?.profile==='personal_brand_content_pilot_v1'&&meeting.plan.actions.length===2&&meeting.plan.actions[0].kind==='evidence_brief'&&meeting.plan.actions[1].kind==='local_draft'&&!!meeting.proposalDigest&&selectedSourceUrls.length===2;
  const approvalCount=(meetingsPaused?0:awaitingApproval.length)+(state?.drafts.filter(draft=>draft.status==='pending').length||0);
  const members=directory?.agents||[];
  const timeline=meeting?[...meeting.messages.map(item=>({kind:'message' as const,time:item.createdAt,id:item.id,item})),...(meeting.artifacts||[]).map(item=>({kind:'artifact' as const,time:item.producedAt,id:item.id,item}))].sort((a,b)=>Date.parse(a.time)-Date.parse(b.time)||a.id.localeCompare(b.id)):[];
  return <div className={'business-shell '+(resizing?'resizing-panel':'')} style={{'--company-panel-width':panelWidth+'px'} as CSSProperties}>
    <header className="business-header"><div className="business-wordmark"><span className="mark">T</span><div>THADDEUS<small>YOUR FIRST EMPLOYEE</small></div></div><nav aria-label="Main views"><button aria-current={mode==='chat'?'page':undefined} onClick={showChat}><MessageCircle size={17}/>Chat</button><button aria-current={mode==='work'?'page':undefined} onClick={()=>setMode('work')}><LayoutList size={17}/>Work</button></nav><div className="business-header-end"><span className={'business-online '+(canWrite?'live':'')}>{canWrite?'Workspace connected':state?.connection.status==='busy'?'Marketing working':state?.connection.status==='auth_required'?'Sign-in needed':'Connecting'}</span><button aria-label="Refresh workspace" onClick={()=>void refresh()}><RefreshCw size={16}/></button><button ref={panelToggle} aria-label={panelOpen?'Hide company panel':'Show company panel'} title="Company panel" aria-expanded={panelOpen} aria-controls="company-panel" onClick={()=>setPanelOpen(!panelOpen)}>{panelOpen?<PanelRightClose size={19}/>:<PanelRightOpen size={19}/>}</button></div></header>
    {(error||readError||!hostOnline)&&<div className="business-alert" role="alert">{error||readError||'The host is offline. Reconnect before making changes.'}<button onClick={()=>{setError('');void refresh();}}>Reconnect</button></div>}
    <div className={'business-body '+(mode==='work'?'work-mode ':'')+(panelOpen?'':'panel-closed')}>
      <main className="business-main" aria-label={mode==='chat'?'Chat workspace':'Work workspace'}>
      {mode==='work'?<><div className="work-meeting-jump"><button onClick={showMeetings}><Users size={16}/>Past meeting records · {meetings.length} <ArrowRight size={15}/></button></div><CompanyWorkspace hostOnline={hostOnline} focus={workFocus} pastMeetingTaskIds={[...pastMeetingTaskIds]} meetingApprovalCount={meetingsPaused?0:awaitingApproval.length} meetingApprovals={!meetingsPaused&&awaitingApproval.length>0&&<section className="work-meeting-approvals" aria-label="Meeting approvals"><h2>Plans awaiting your approval</h2>{awaitingApproval.map(m=><button key={m.id} onClick={()=>openMeeting(m)}><ShieldCheck size={20}/><span><strong>{m.title}</strong><small>{m.plan!.resources}</small></span><span>Review plan <ArrowRight size={15}/></span></button>)}</section>}/></>:chatView==='meetings'?<MeetingArchive meetings={meetings} onOpen={openMeeting} onStart={()=>setStarting(true)} canStart={!!owner&&hostOnline}/>:<>
        <div className="business-conversation-title"><div><p className="eyebrow">{meeting?'PAST MEETING RECORD':member?.departmentId?directory?.departments.find(d=>d.id===member.departmentId)?.name?.toUpperCase():'MARKETING'}</p><h1>{meeting?meeting.title:member?.name||state?.employee.name||'Marketing agent'}</h1><p>{meeting?<><span className="meeting-stage">{stageLabel[meeting.stage]}</span> Saved CEO · Marketing · owner session record</>:member?.runtimeKey===null?'This member needs a connection before joining conversations.':'Your employee’s direct conversation. Turn decisions into work.'}</p></div><div className="conversation-actions">{meeting&&<><button className="business-meeting-button" onClick={showMeetings}><ArrowLeft size={16}/>All records</button><button className="business-meeting-button" onClick={()=>downloadMeeting(meeting)}><Download size={16}/>Audit JSON</button></>}{!meetingsPaused&&<button className="business-meeting-button" disabled={!owner||!hostOnline} onClick={()=>setStarting(true)}><CalendarPlus size={17}/>Start meeting</button>}</div></div>
        {!state?<div className="company-empty">Opening your conversations…</div>:meeting?<section className="meeting-conversation" aria-label="Meeting conversation"><MeetingProgress meeting={meeting}/><MeetingAudit meeting={meeting} onArtifact={openArtifact} onTask={id=>work('tasks',undefined,id)}/>
          <div className="meeting-transcript" ref={scrolling}><article className="meeting-agenda-message"><span className="meeting-avatar">M</span><div><strong>Meeting opened <time>{readableTime(meeting.createdAt)}</time></strong><h2>{meeting.title}</h2><p>{meeting.agenda}</p><small>CEO asks and reviews. Marketing proposes and delivers. You retain veto power.</small></div></article>
          {timeline.map(entry=>entry.kind==='message'?<article className={'meeting-message '+(entry.item.speaker==='You'?'from-owner':'')} key={entry.id}><span className={'meeting-avatar '+(entry.item.speaker==='CEO'?'ceo':'')}>{entry.item.speaker==='CEO'?'C':entry.item.speaker==='Marketing'?'M':entry.item.speaker==='You'?'O':'T'}</span><div><div className="meeting-message-byline"><strong>{entry.item.speaker==='You'?'Owner session':entry.item.speaker}</strong><small>{entry.item.speaker==='CEO'?'Chair · questions and review':entry.item.speaker==='Marketing'?'Planner · proposals':entry.item.speaker==='You'?'Submitted through owner access':'Meeting participant'}</small><time>{readableTime(entry.item.createdAt)}</time></div><Markdown components={{img:()=>null}}>{entry.item.content}</Markdown></div></article>:<article className="meeting-artifact" id={'meeting-artifact-'+entry.item.id} key={entry.id}><div className="meeting-message-byline"><strong>{entry.item.kind==='local_draft'?'Local draft':'Evidence brief'}</strong><time>{readableTime(entry.item.producedAt)}</time></div><p>{entry.item.ownerAccepted?`Accepted by ${entry.item.acceptedBy}`:'Produced for owner review'} · Task {entry.item.taskId.slice(0,8)} · Digest {entry.item.digest.slice(0,12)}</p><Markdown components={{img:()=>null}}>{entry.item.content}</Markdown>{entry.item.kind==='local_draft'&&!entry.item.ownerAccepted&&owner&&<button className="primary" disabled={busy||!hostOnline} onClick={()=>void act('accept-artifact',entry.item.id)}>Accept this local draft</button>}{entry.item.sourceUrls?.map(url=><p key={url}><a href={url} target="_blank" rel="noreferrer">Source: {url}</a></p>)}</article>)}
          {meetingBusy&&<p className="meeting-thinking" role="status">The team is considering the meeting…</p>}{meeting.error&&<p className="company-error" role="alert">{meeting.error}</p>}</div>
          {meetingsPaused?<div className="meeting-ended"><CheckCircle2 size={18}/><span>Meeting turns and new assignments are paused for the single-employee MVP. This record remains available for audit.</span><button onClick={showMeetings}>All records <ArrowRight size={15}/></button><button onClick={()=>work('tasks')}>Open board <ArrowRight size={15}/></button></div>:ended?<div className="meeting-ended"><CheckCircle2 size={18}/><span>{meeting.stage==='vetoed'?'Plan vetoed. Pending work is stopped; an active remote outcome may still be unknown.':'Notes are saved. Follow the assignments in Work.'}</span><button onClick={showMeetings}>All meetings <ArrowRight size={15}/></button><button onClick={()=>work('tasks')}>Open board <ArrowRight size={15}/></button></div>:<div className="meeting-composer"><div className="meeting-next-step"><span>{meeting.review?.verdict==='revise'?'The CEO requested changes. Add direction or develop a revised plan.':meeting.review?.verdict==='accept'?'The CEO recommends this plan. Review the owner grant in the sidebar.':'Discuss the need, then ask Marketing to develop a plan.'}</span><button disabled={meetingBusy||!canWrite||!owner} onClick={()=>void act('propose')}>{meeting.plan?'Revise plan & review':'Develop plan & review'} <ArrowRight size={14}/></button></div><form onSubmit={e=>{e.preventDefault();void discuss();}}><textarea aria-label="Message to meeting" value={draft} onChange={e=>changeDraft(e.target.value)} disabled={meetingBusy||!canWrite||!owner} placeholder="Give direction, answer the CEO, or challenge the plan…"/><div><small>CEO responds to your message · Enter a clear outcome</small><button className="primary" disabled={meetingBusy||!canWrite||!owner||!draft.trim()}><Send size={16}/>Send</button></div></form></div>}
        </section>:member?.runtimeKey===null?<div className="company-empty"><Users size={28}/><h2>Ready for a future colleague</h2><p>Connect this member’s runtime to start a conversation.</p><button onClick={()=>work('team')}>Manage team</button></div>:<MarketingDiscussion state={state} canWrite={!!canWrite} onRefresh={refresh}/>}
      </>}
      </main>
      {panelOpen&&<><PanelResize width={panelWidth} onChange={resizePanel} onDragging={setResizing}/><button className="company-panel-backdrop" aria-label="Dismiss company panel" onClick={closePanel}/><aside id="company-panel" className="business-sidebar" aria-label="Company sidebar" onKeyDown={event=>{if(event.key==='Escape')closePanel();}}><div className="business-panel-heading"><span>Company panel</span><button aria-label="Close company panel" onClick={closePanel}><X size={17}/></button></div><div className="business-panel-identity"><Raven state={meetingBusy?'listening':'idle'}/><strong>{meeting?'Meeting room':'Your first employee'}</strong><span><i className={canWrite?'live':''}/>{meeting?'CEO · Marketing · You':canWrite?'Team connected':'Connection pending'}</span></div><nav className="business-side-tabs" aria-label="Sidebar views"><button aria-pressed={sideTab==='glance'} onClick={()=>setSideTab('glance')}>At a glance</button><button aria-label="All members" aria-pressed={sideTab==='members'} onClick={()=>setSideTab('members')}><Users size={15}/><span>Members</span></button><button aria-label="Department conversations" aria-pressed={sideTab==='conversations'} onClick={()=>setSideTab('conversations')}><MessageCircle size={15}/><span>Chats</span></button></nav>
      {sideTab==='glance'?<>
        <section className="business-glance"><p className="eyebrow">TODAY’S BUSINESS</p><div className="business-metrics"><button onClick={()=>work(draftReviewPending?'tasks':approvalCount?'approvals':'tasks',undefined,undefined,draftReviewArtifact?.id)}><strong>{pending.length+approvalCount+(draftReviewPending?1:0)}</strong><span>Decisions</span></button><button onClick={()=>work('tasks')}><strong>{active.length}</strong><span>In progress</span></button><button onClick={showMeetings}><strong>{meetings.length}</strong><span>Past records</span></button></div></section>
        {meeting?<><MeetingRecap meeting={meeting} state={state!} onTask={id=>work('tasks',undefined,id)} onArtifact={openArtifact} onApproval={()=>document.getElementById('meeting-owner-grant')?.scrollIntoView({behavior:'smooth',block:'center'})}/><section className="business-side-section"><div className="side-section-title"><h2>Meeting agenda</h2><span>{stageLabel[meeting.stage]}</span></div><p className="meeting-sidebar-agenda">{meeting.agenda}</p><details><summary>Company ethos <ChevronDown size={14}/></summary><p>{meeting.ethos}</p></details></section><section className="business-side-section action-plan"><div className="side-section-title"><h2>Action plan</h2>{meeting.plan&&<span>v{meeting.plan.revision}</span>}</div>{meeting.plan?<><p>{meeting.plan.summary}</p><ol>{meeting.plan.actions.map((item,i)=><li key={i}><strong>{item.title}</strong><small>{item.outcome}</small><span>Marketing · {item.state.replaceAll('_',' ')}</span>{item.taskId&&<button onClick={()=>work('tasks',undefined,item.taskId!)}>View on board <ArrowRight size={13}/></button>}</li>)}</ol><div className="meeting-resource-gate gated"><ShieldCheck size={16}/><div><strong>{meeting.grant?meeting.grant.revoked?'Owner grant revoked':'Owner grant recorded':'Owner approval required for every plan'}</strong><p>{meeting.plan.resources}</p></div></div>{meeting.review&&<div className="meeting-review-note"><strong>CEO · {meeting.review.verdict==='accept'?'Recommended':'Revise'}</strong><p>{meeting.review.rationale}</p>{meeting.review.questions.length>0&&<div className="meeting-open-questions"><strong>Open questions</strong><ul>{meeting.review.questions.map((q,i)=><li key={i}>{q}</li>)}</ul></div>}</div>}
        {meeting.grant&&<div className="meeting-grant-record"><strong>Owner grant {meeting.grant.id.slice(0,8)} · {meeting.grant.revoked?'revoked':'recorded'}</strong><p>{meeting.grant.approver} approved plan digest {meeting.grant.planDigest.slice(0,12)}. {meeting.grant.dispatchAttempts}/{meeting.grant.maxDispatchAttempts} worker dispatches used.</p></div>}
        {!meetingsPaused&&owner&&meeting.stage==='reviewed'&&meeting.review?.verdict==='accept'&&!meeting.grant&&<p className="meeting-fixed-profile">Restricted pilot: your personal brand selling configurable marketing agents. Provisional audience: independent technical founders selling B2B software. This approval does not change brief v{state?.profile.version}.</p>}
        {!meetingsPaused&&owner&&meeting.stage==='reviewed'&&meeting.review?.verdict==='accept'&&meeting.plan.profile!=='personal_brand_content_pilot_v1'&&<p className="company-error">This plan is outside the restricted pilot profile. Ask Marketing for a revised plan before approval.</p>}
        {!meetingsPaused&&owner&&meeting.stage==='reviewed'&&meeting.review?.verdict==='accept'&&!meeting.grant&&<div id="meeting-owner-grant" className="meeting-grant-approval"><h3>Approve this exact local job</h3><p>Plan v{meeting.plan.revision} · digest {meeting.proposalDigest?.slice(0,12)||'unavailable'}</p><p>Two sequential tasks: evidence brief, then one local draft. Two exact public sources; saved meeting artifact and scoped task updates. No shell, browser, messaging, account actions, posting, purchases, or scheduling.</p><p>Maximum 2 worker dispatches, 2 assigned tasks, 10 minute execution deadline. Model: {state?.employee.model}; no fallback. Model calls within a top-level turn and charges are not guaranteed by this limit.</p><fieldset><legend>Select two existing source records</legend>{meetingSources.map(source=><label key={source.url}><input type="checkbox" checked={selectedSourceUrls.includes(source.url)} onChange={event=>setSelectedSourceUrls(current=>event.target.checked?[...current,source.url]:current.filter(url=>url!==source.url))}/><span>{source.title}<small>{source.url}</small></span></label>)}</fieldset>{meetingSources.length<2&&<p>Two eligible public source records are required before this plan can run.</p>}{meeting.plan.actions.some(a=>a.kind==='unclassified')&&<p>This plan needs the restricted evidence brief and local draft task types. Revise it first.</p>}<button className="primary" disabled={meetingBusy||!canWrite||!readyToApprove} onClick={()=>void act('approve',undefined,{planDigest:meeting.proposalDigest,sourceUrls:selectedSourceUrls})}>Approve scope & assign work</button></div>}
        </>:<div className="meeting-plan-empty"><LayoutList size={25}/><p>The plan takes shape here as the meeting progresses.</p><small>Each action will have an owner and a clear outcome.</small></div>}
        {owner&&meeting.stage!=='vetoed'&&(meeting.stage!=='closed'||meeting.plan?.actions.some(a=>a.state==='queued'||a.state==='working'||a.state==='proposed'))&&<button className="meeting-veto" disabled={!hostOnline} onClick={()=>void act('veto')}>Veto plan & stop pending work</button>}{meeting.plan?.actions.some(a=>a.state==='working')&&<small className="meeting-running-note">An active turn may still finish after a veto. Its result remains in the task record.</small>}</section></>:<>
          <section className="business-side-section"><div className="side-section-title"><h2>Next actions</h2><button onClick={()=>work('tasks')}>Board <ArrowRight size={14}/></button></div>
            {draftReviewPending&&<button className="business-next-action" onClick={()=>work('tasks',undefined,undefined,draftReviewArtifact?.id)}><span className="company-priority-dot high"/><span><strong>Review Marketing’s draft angles</strong><small>Saved assignment · your decision</small></span></button>}
            {recent.map(task=><button className="business-next-action" key={task.id} onClick={()=>work('tasks',undefined,task.id)}><span className={'company-priority-dot '+task.priority}/><span><strong>{task.title}</strong><small>{task.status==='needs_you'?'Needs your decision':task.status==='working'?'Marketing is working':'Ready for Marketing'}</small></span></button>)}
            {!draftReviewPending&&!recent.length&&<p className="sidebar-muted">Agreed assignments will appear here.</p>}
          </section>
          <section className="business-side-section"><div className="side-section-title"><h2>Past decisions</h2><FileText size={17}/></div><p className="sidebar-muted">Review saved pilot meeting notes and results when you need the history.</p><button className="business-wide-button" onClick={showMeetings}>Open past meetings <ArrowRight size={15}/></button></section>
          <section className="business-side-section"><div className="side-section-title"><h2>Saved work</h2><FileText size={17}/></div><p className="sidebar-muted">Research, replies, drafts, and decision records.</p><button className="business-wide-button" onClick={()=>work('records')}>Open records <ArrowRight size={15}/></button><button className="business-wide-button" onClick={()=>work('wiki')}>Open company wiki <ArrowRight size={15}/></button></section>
        </>}
      </>:sideTab==='members'?<section className="business-side-section"><div className="side-section-title"><h2>All members</h2><button onClick={()=>work('team')}>Manage <ArrowRight size={14}/></button></div>{members.map(item=><button key={item.id} className="business-member" onClick={()=>{setMemberId(item.id);setMeetingId(null);setMode('chat');}}><span className={'meeting-avatar '+(item.kind==='manager'?'ceo':'')}>{item.name.slice(0,1)}</span><span><strong>{item.name}</strong><small>{item.role}</small><em>{item.runtimeKey==='meeting-ceo'?'Meeting chair':item.runtimeKey?'Connected':'Setup needed'}</em></span></button>)}</section>:<section className="business-side-section"><div className="side-section-title"><h2>Conversations</h2></div>{directory?.departments.map(department=><div className="department-conversations" key={department.id}><h3>{department.name}</h3>{directory.agents.filter(a=>a.departmentId===department.id).map(item=><button key={item.id} aria-pressed={!meetingId&&memberId===item.id} onClick={()=>{setMemberId(item.id);setMeetingId(null);setMode('chat');}}><MessageCircle size={15}/>{item.name}</button>)}</div>)}<h3 className="sidebar-subheading">Past meeting records</h3>{meetings.map(m=><button key={m.id} className="sidebar-meeting-link" aria-pressed={meetingId===m.id} onClick={()=>openMeeting(m)}><strong>{m.title}</strong><small>{stageLabel[m.stage]}</small></button>)}{!meetings.length&&<p className="sidebar-muted">Past records will appear here when available.</p>}</section>}
      <div className="business-sidebar-foot"><ShieldCheck size={14}/><span>Marketing works directly with you. Past decisions remain available for audit.</span></div></aside></>}
    </div>
    {starting&&<StartMeeting ethos={state?.profile.guardrails||''} model={state?.employee.model||'the configured model'} onClose={()=>setStarting(false)} onStart={async fields=>{const created=await api<Meeting>('/meetings',fields);setMeetings(items=>[created,...items.filter(m=>m.id!==created.id)]);openMeeting(created);setStarting(false);setBusy(true);try{await command('ask-ceo',undefined,created);}catch(e){setError((e as Error).message);}finally{setBusy(false);void refresh();}}}/>}
  </div>;
}
