import {useState} from 'react';
import Markdown from 'react-markdown';
import {ShieldCheck,ArrowUpRight,Check,PanelRightClose,FileText} from 'lucide-react';
import type {DelegationJob,Run} from '../types';
import {Raven,StateIcon,names} from './Raven';
import {Reconciliation} from './Reconciliation';
import {TaskQuestion} from './TaskQuestion';
import {ProposalChecks} from './ProposalChecks';
import {ArtifactChecks} from './ArtifactChecks';
import {ArtifactImports} from './ArtifactImports';
import {CheckpointRecovery} from './CheckpointRecovery';
import {PublicResearchActivity} from './PublicResearchActivity';
import {TaskGuidance} from './TaskGuidance';
type Props={run:Run;jobs:DelegationJob[];owner:boolean;trace:any[];online:boolean;busy:boolean;onBack:()=>void;onPage:(path:string)=>void;onDecision:(allow:boolean)=>void;onCancel:()=>void;onResume:()=>void;onReconcile:()=>Promise<unknown>};
export function TaskDetail({run,jobs,owner,trace,online,busy,onBack,onPage,onDecision,onCancel,onResume,onReconcile}:Props){
 const [rail,setRail]=useState(true);
 const connectedTool=run.connectedTools?.find(tool=>tool.modelName===run.approval?.action.name&&tool.connectorId===run.approval?.action.path);
 const delegationApproval=run.approval?.action.name==='delegation_schedule_reminder';
 const todoApproval=run.approval?.action.name==='todo_batch_create';
 const managementApproval=run.approval?.action.name==='delegation_cancel'||run.approval?.action.name==='delegation_reschedule_reminder';
 const reminder=delegationApproval?(()=>{try{return JSON.parse(run.approval?.action.content||'{}') as {title?:string;message?:string;dueUtc?:string;timeZone?:string};}catch{return {};}})():null;
 const todoBatch=todoApproval?(()=>{try{return JSON.parse(run.approval?.action.content||'{}') as {sourceReference?:string;items?:{title?:string;notes?:string;due?:string|null;ambiguity?:string|null}[]};}catch{return {};}})():null;
 const management=managementApproval?(()=>{try{return JSON.parse(run.approval?.action.content||'{}') as {jobId?:string;version?:number;dueUtc?:string;timeZone?:string};}catch{return {};}})():null;
 const managedJob=jobs.find(job=>job.id===(management?.jobId||run.approval?.action.path));
 const approvalTitle=delegationApproval?'Reminder review':todoApproval?'To-do batch review':managementApproval?(run.approval?.action.name==='delegation_cancel'?'Cancel delegated work':'Reschedule reminder'):connectedTool?'Connected action review':run.state==='awaitingApproval'?'Your permission, precisely.':'Write proposal';
 const approvalSubtitle=delegationApproval?'Windows notification + unread in-app result':todoApproval?`${todoBatch?.items?.length??0} editable items from ${todoBatch?.sourceReference??'supplied reading'}`:managementApproval?(managedJob?.title||'Current delegated job'):connectedTool?`${connectedTool.connectorName} · ${connectedTool.remoteName}`:`${run.approval?.action.name} · ${run.approval?.action.path}`;
 const denyLabel=delegationApproval?'Do not schedule':todoApproval?'Create nothing':managementApproval?'Keep unchanged':connectedTool?'Deny action':'Deny write';
 const approveLabel=delegationApproval?'Schedule reminder':todoApproval?'Create these To-dos':managementApproval?(run.approval?.action.name==='delegation_cancel'?'Cancel this job':'Use this new time'):connectedTool?'Approve exact action':'Approve exact write';
 const reviewReady=!run.research||(run.research.phase==='awaiting-approval'&&run.research.review?.approvalId===run.approval?.id);
 const answerReady=!run.research||run.research.phase==='awaiting-input';
 return <><section className="task-main"><button className="text-button" onClick={onBack}>← Back to conversation</button><p className="eyebrow">TASK RECEIPTS · {run.goal.kind==='edit'?'YOUR EDIT':run.goal.provider.kind==='scripted'?'SIMULATED MODEL':'LIVE MODEL'}</p><h1>{run.goal.objective}</h1><div className="task-status"><span className={'badge '+run.state}><StateIcon state={run.state}/>{names[run.state]}</span><Raven state={online?run.state:'disconnected'}/></div><p className="lead">{run.summary}</p>{run.research&&<section className="receipt-block" aria-label="Research progress"><p role="status">{run.research.message}</p>{run.research.review&&<p>Artifact readback matched: {run.research.review.artifact}</p>}{run.research.failureCode&&<small>Control receipt: {run.research.failureCode}</small>}</section>}
  {!!run.preparedContext?.memories?.length&&<details aria-label="Remembered context prepared for this task"><summary>Frozen remembered context · {run.preparedContext.memories.length}</summary><p>Historical task context. Current notes and remembered entries may have changed.</p>{run.preparedContext.memories.map(entry=><article className="memory-entry" key={entry.id}><p>{entry.statement}</p><blockquote>{entry.source?.quote}</blockquote><p><small>Memory {entry.id} · version {entry.version}</small></p><button className="text-button" disabled={!online} onClick={()=>onPage(entry.source!.path)}>Open current source: {entry.source?.path}</button><p><small>Source version {entry.source?.version}</small></p></article>)}</details>}
  {run.approval&&<section className="approval-card"><div className="card-heading"><ShieldCheck/><div><h2>{approvalTitle}</h2><p>{approvalSubtitle}</p></div></div>{delegationApproval?<div className="delegation-review"><h3>{reminder?.title||'Reminder'}</h3><p>{reminder?.message}</p><dl><dt>When</dt><dd>{reminder?.dueUtc?new Date(reminder.dueUtc).toLocaleString():'Unknown'}</dd><dt>Timezone</dt><dd>{reminder?.timeZone}</dd><dt>Authority</dt><dd>Schedule this exact reminder once</dd></dl><p className="muted">The reminder is persisted only after approval. This computer and the Thaddeus host must remain awake at delivery time.</p></div>:todoApproval?<div className="delegation-review"><p>Approving creates only the items below. Each remains editable and retains its source reference.</p>{todoBatch?.items?.map((item,index)=><article className="receipt-block" key={`${item.title}-${index}`}><h3>{item.title||`To-do ${index+1}`}</h3>{item.notes&&<p>{item.notes}</p>}<dl><dt>Due</dt><dd>{item.due||'Unresolved'}</dd>{item.ambiguity&&<><dt>Needs review</dt><dd>{item.ambiguity}</dd></>}</dl></article>)}</div>:managementApproval?<div className="delegation-review"><h3>{managedJob?.title||'Delegated work'}</h3><dl><dt>Current state</dt><dd>{managedJob?.state||'Changed or unavailable'}</dd><dt>Current time</dt><dd>{managedJob?.nextRunUtc?new Date(managedJob.nextRunUtc).toLocaleString():'No future run'}</dd>{run.approval.action.name==='delegation_reschedule_reminder'&&<><dt>New time</dt><dd>{management?.dueUtc?new Date(management.dueUtc).toLocaleString():'Unknown'}</dd><dt>Timezone</dt><dd>{management?.timeZone}</dd></>}</dl><p className="muted">The job version is bound to this approval. If it changes before you approve, Thaddeus will refuse the stale request.</p></div>:<><p>{connectedTool?`Effect: ${connectedTool.effect}. The credential stays on this host. Approving sends only these arguments to the configured MCP server.`:run.goal.kind==='edit'?'Your explicit edit and its recorded content.':'This exact Markdown is bound to the recorded approval.'}</p>{connectedTool?<div className="draft"><pre>{JSON.stringify(JSON.parse(run.approval.action.content||'{}'),null,2)}</pre></div>:<div className="draft"><Markdown components={{a:({href,children})=>href && /^(notes|plans)\/[a-z0-9-]+\.md$/.test(href)?<button className="text-button" onClick={()=>onPage(href)}>{children}</button>:<a href={href}>{children}</a>}}>{run.approval.action.content}</Markdown></div>}</>}<details><summary>Exact arguments & approval binding</summary><pre>{JSON.stringify(run.approval,null,2)}</pre></details>{run.state==='awaitingApproval'&&<div className="approval-actions"><span>Expires {new Date(run.approval.expires).toLocaleTimeString()}</span><button disabled={busy||!online||!reviewReady} onClick={()=>onDecision(false)}>{denyLabel}</button><button className="primary" disabled={busy||!online||!reviewReady} onClick={()=>onDecision(true)}><Check size={16}/> {approveLabel}</button></div>}</section>}
  {run.state==='needsAttention'&&run.research?.phase==='attention'&&run.approval?.decision!=='approved'&&<CheckpointRecovery key={run.id} run={run} owner={owner} online={online} onChanged={onReconcile}/>}
  {run.question&&<TaskQuestion key={run.question.id} runId={run.id} question={run.question} online={online} ready={answerReady} continues={!!run.research} blockedReason={run.research?.phase==='attention'?'This task needs recovery review before it can accept your answer.':undefined} onChanged={onReconcile}/>}
  {run.state==='needsAttention'&&run.approval&&(!run.research||(run.research.phase==='attention'&&run.research.review&&run.approval.decision==='approved'))&&<Reconciliation run={run} online={online} onChanged={onReconcile}/>}
  {run.outputPath&&<button className="primary" onClick={()=>onPage(run.outputPath!)}>Open editable plan <ArrowUpRight size={16}/></button>}
  {(['queued','running','awaitingApproval','awaitingInput','paused'].includes(run.state)||(run.research&&run.research.phase!=='finished'))&&<button className="text-button" disabled={busy||!online} onClick={onCancel}>Cancel task</button>}
  {run.state==='paused'&&(!run.research||run.research.phase==='paused')&&<button disabled={busy||!online} onClick={onResume}>Resume safe work</button>}
  {run.research&&(run.research.phase==='working'||run.executionCommands?.some(command=>command.kind==='steer'))&&<TaskGuidance key={run.id} run={run} online={online} onChanged={onReconcile}/>}
  <PublicResearchActivity run={run}/>
  <ProposalChecks reviews={run.nativeProposals??[]} repairs={run.repairs}/>
  <ArtifactChecks checks={run.artifactChecks??[]}/>
  <ArtifactImports imports={run.artifactImports??[]}/>
  <section className="receipt-block"><h2>What was checked</h2>{run.validation?.checks.map(c=><p key={c} className="check"><Check size={16}/>{c}</p>)}{(!run.validation||run.validation.unverified.length>0)&&<p className="muted">{run.validation?.unverified.join(' · ')||'No independent validation was recorded.'}</p>}</section>
  <details className="trace"><summary>Replay recorded events · {trace.length} receipts · no re-execution</summary>{trace.map(e=><details key={e.eventId}><summary>{e.sequence}. {e.type} · {new Date(e.timestamp).toLocaleTimeString()}</summary><pre>{JSON.stringify(e,null,2)}</pre></details>)}</details></section>
  <aside className={'evidence-rail '+(!rail?'collapsed':'')}><button className="text-button" onClick={()=>setRail(!rail)}><PanelRightClose size={16}/>{rail?'Collapse receipts':'Show receipts'}</button>{rail&&<><h3>Behind the outcome</h3><p className="eyebrow">SOURCE EVIDENCE</p>{run.evidence.map(e=><details key={e.path} className="source"><summary><FileText size={17}/>{e.path}</summary><button className="text-button" onClick={()=>onPage(e.path)}>Open current source page <ArrowUpRight size={14}/></button><pre>{e.content}</pre><small>SHA-256 {e.hash}</small></details>)}<p className="eyebrow">RUN SNAPSHOT</p><dl><dt>Provider</dt><dd>{run.goal.provider.kind}</dd><dt>Model</dt><dd>{run.goal.provider.model}</dd><dt>Reasoning</dt><dd>{run.goal.provider.reasoning}</dd><dt>Model calls</dt><dd>{run.modelCalls} / {run.goal.limits.modelCalls}</dd><dt>Tool calls</dt><dd>{run.toolCalls} / {run.goal.limits.toolCalls}</dd><dt>Repairs</dt><dd>{run.repairs}</dd><dt>Tokens in / out</dt><dd>{run.inputTokens??'unknown'} / {run.outputTokens??'unknown'}</dd><dt>Charged / token budget</dt><dd>{run.chargedTokens??0} / {run.goal.limits.maxTotalTokens}</dd><dt>Accounting</dt><dd>{run.tokenAccounting||"No dispatch"}</dd><dt>Cost</dt><dd>Unknown</dd><dt>Elapsed to last event</dt><dd>{((+new Date(run.updated)-+new Date(run.created))/1000).toFixed(1)}s</dd></dl><small>Waiting for approval is included in wall time. No invented progress percentages.</small></>}</aside></>;
}
